"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { SportsNav } from "@/components/dashboard-chrome";
import styles from "./game-slate.module.css";

export type GameSlateSport = "mlb"|"nfl"|"cfb"|"nba"|"wnba"|"nhl"|"soccer"|"cbb";
type Game={id:string;date:string;awayTeam:string;awayAbbr:string;awayLogo?:string|null;awayScore?:number|string|null;awayRecord?:string;homeTeam:string;homeAbbr:string;homeLogo?:string|null;homeScore?:number|string|null;homeRecord?:string;state:"pre"|"in"|"post";status:string;venue?:string};
type RosterPlayer={playerId:string;playerName:string;position:string;starter:boolean;active:boolean;headshot:string};
type Roster={teamId:string;teamName:string;teamAbbr:string;teamLogo:string;side:"away"|"home"|"";players:RosterPlayer[]};
type RankingRow={rank?:number;playerId?:string|number;playerName?:string;teamName?:string;matchup?:string;market?:string;marketLabel?:string;sportsbookLine?:number|null;modelProjection?:number|null;giScore?:number|null;modelProbability?:number|null;headshot?:string};

const LABELS:Record<GameSlateSport,string>={mlb:"MLB",nfl:"NFL",cfb:"CFB",nba:"NBA",wnba:"WNBA",nhl:"NHL",soccer:"Soccer",cbb:"CBB"};
const ICONS:Record<GameSlateSport,string>={mlb:"⚾",nfl:"🏈",cfb:"🏈",nba:"🏀",wnba:"🏀",nhl:"🏒",soccer:"⚽",cbb:"🏀"};
const MARKET_CONFIG:Record<GameSlateSport,Array<[string,string]>>={
 mlb:[["home_runs","Home Runs"],["hits","Hits"],["total_bases","Total Bases"],["strikeouts","Pitcher Strikeouts"]],
 nfl:[["passing_yards","Passing Yards"],["receiving_yards","Receiving Yards"],["rushing_yards","Rushing Yards"],["receptions","Receptions"]],
 cfb:[["passing_yards","Passing Yards"],["rushing_yards","Rushing Yards"],["receiving_yards","Receiving Yards"],["receptions","Receptions"]],
 nba:[["points","Points"],["rebounds","Rebounds"],["assists","Assists"],["pts_rebs_asts","PRA"]],
 wnba:[["points","Points"],["rebounds","Rebounds"],["assists","Assists"],["pts_rebs_asts","PRA"]],
 nhl:[["shots_on_goal","Shots on Goal"],["points","Points"],["goals","Goals"],["goalie_saves","Goalie Saves"]],
 soccer:[["shots_on_target","Shots on Target"],["shots","Shots"],["saves","Goalkeeper Saves"],["goals","Goals"]],
 cbb:[["points","Points"],["rebounds","Rebounds"],["assists","Assists"],["pts_rebs_asts","PRA"]],
};

const clean=(v:unknown)=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function localDay(value:string){const d=new Date(value);if(Number.isNaN(d.getTime()))return"";const p=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Toronto",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const g=(t:string)=>p.find(x=>x.type===t)?.value||"";return`${g("year")}-${g("month")}-${g("day")}`}
function dayLabel(value:string){const d=new Date(value);if(Number.isNaN(d.getTime()))return"Upcoming";return new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",weekday:"long",month:"long",day:"numeric"}).format(d)}
function timeLabel(value:string){const d=new Date(value);if(Number.isNaN(d.getTime()))return"Time TBD";return`${new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",hour:"numeric",minute:"2-digit",hour12:true}).format(d)} ET`}
function initials(name:string){const p=name.split(/\s+/).filter(Boolean);return(p.length>1?`${p[0][0]}${p.at(-1)?.[0]||""}`:p[0]?.slice(0,2)||"SS").toUpperCase()}
function gameMatchesRow(game:Game,row:RankingRow){const matchup=clean(row.matchup),team=clean(row.teamName),away=[clean(game.awayTeam),clean(game.awayAbbr)].filter(Boolean),home=[clean(game.homeTeam),clean(game.homeAbbr)].filter(Boolean);if(away.some(v=>matchup.includes(v))&&home.some(v=>matchup.includes(v)))return true;return[...away,...home].some(v=>v&&team===v)}
function playerHref(sport:GameSlateSport,row:RankingRow,game:Game){const id=encodeURIComponent(String(row.playerId||clean(row.playerName)));const qs=new URLSearchParams({name:row.playerName||"Player",team:row.teamName||"",matchup:`${game.awayTeam} @ ${game.homeTeam}`,market:row.market||"",line:String(row.sportsbookLine??""),projection:String(row.modelProjection??""),gi:String(row.giScore??""),prob:String(row.modelProbability??"")});return`/${sport}/player/${id}?${qs.toString()}`}
function rosterPlayerHref(sport:GameSlateSport,p:RosterPlayer,r:Roster,g:Game){const qs=new URLSearchParams({name:p.playerName,team:r.teamName,matchup:`${g.awayTeam} @ ${g.homeTeam}`,img:p.headshot||""});return`/${sport}/player/${encodeURIComponent(p.playerId)}?${qs.toString()}`}

async function fetchRankings(sport:GameSlateSport,league:string,game:Game,signal:AbortSignal):Promise<RankingRow[]>{
 const markets=MARKET_CONFIG[sport];
 if(sport==="mlb"){const r=await fetch("/api/mlb/rankings",{cache:"no-store",signal});if(!r.ok)return[];const p=await r.json();const rows:RankingRow[]=[];for(const[market,label]of markets){for(const row of p?.batter?.[market]||p?.pitcher?.[market]||[])rows.push({...row,market,marketLabel:label})}return rows.filter(row=>gameMatchesRow(game,row)).sort((a,b)=>Number(b.giScore||0)-Number(a.giScore||0)).slice(0,10)}
 if(sport==="soccer"){const r=await fetch(`/api/soccer/dashboard?league=${encodeURIComponent(league)}`,{cache:"no-store",signal});if(!r.ok)return[];const p=await r.json();const rows:RankingRow[]=[];for(const[market,label]of markets)for(const raw of p?.rankings?.[market]||[])rows.push({...raw,playerId:raw?.playerId,playerName:raw?.playerName,teamName:raw?.team,sportsbookLine:raw?.marketLine,modelProjection:raw?.projection,market,marketLabel:label});return rows.filter(row=>gameMatchesRow(game,row)).sort((a,b)=>Number(b.giScore||0)-Number(a.giScore||0)).slice(0,10)}
 const blocks=await Promise.all(markets.map(async([market,label])=>{const url=sport==="cfb"?`/api/cfb/rankings-board?market=${encodeURIComponent(market)}&slate=all`:`/api/${sport}/rankings?market=${encodeURIComponent(market)}`;try{const r=await fetch(url,{cache:"no-store",signal});if(!r.ok)return[];const p=await r.json();return(p?.rows||[]).map((row:RankingRow)=>({...row,market,marketLabel:label}))}catch{return[]}}));return blocks.flat().filter(row=>gameMatchesRow(game,row)).sort((a,b)=>Number(b.giScore||0)-Number(a.giScore||0)).slice(0,10)
}

function BrandHeader({sport}:{sport:GameSlateSport}){return<><div className={styles.brand}><img src="/brand/sach-sports-crown-logo.png" alt=""/><strong><span>SACH</span> SPORTS</strong></div><SportsNav active={sport}/></>}
function TeamLogo({src,name}:{src?:string|null;name:string}){return src?<img src={src} alt=""/>:<div className={styles.logoFallback}>{initials(name)}</div>}

function ExpandedGame({sport,league,game}:{sport:GameSlateSport;league:string;game:Game}){
 const[rosters,setRosters]=useState<Roster[]>([]),[rankings,setRankings]=useState<RankingRow[]>([]),[loading,setLoading]=useState(true),[teamFilter,setTeamFilter]=useState<"all"|"away"|"home">("all"),[rosterSide,setRosterSide]=useState<"away"|"home">("away"),[showFull,setShowFull]=useState(false);
 useEffect(()=>{const c=new AbortController();setLoading(true);Promise.all([fetch(`/api/game-slate-detail?sport=${encodeURIComponent(sport)}&gameId=${encodeURIComponent(game.id)}&league=${encodeURIComponent(league)}`,{cache:"no-store",signal:c.signal}).then(r=>r.ok?r.json():{rosters:[]}).then(p=>p?.rosters||[]).catch(()=>[]),fetchRankings(sport,league,game,c.signal).catch(()=>[])]).then(([rr,rk])=>{if(c.signal.aborted)return;setRosters(rr);setRankings(rk);setLoading(false)});return()=>c.abort()},[sport,league,game.id]);
 const filtered=rankings.filter(row=>{if(teamFilter==="all")return true;const target=teamFilter==="away"?[clean(game.awayTeam),clean(game.awayAbbr)]:[clean(game.homeTeam),clean(game.homeAbbr)];const team=clean(row.teamName);return target.some(v=>v&&(team===v||team.includes(v)||v.includes(team)))});
 const away=rosters.find(r=>r.side==="away")||rosters.find(r=>clean(r.teamName).includes(clean(game.awayTeam)))||rosters[0];const home=rosters.find(r=>r.side==="home")||rosters.find(r=>clean(r.teamName).includes(clean(game.homeTeam)))||rosters[1];const active=rosterSide==="away"?away:home;const visible=active?.players?(showFull?active.players:active.players.slice(0,12)):[];
 return<div className={styles.expanded}>
  <section className={styles.intelBlock}><h3>🔥 Game Intelligence</h3><div className={styles.teamContext}><div><span>AWAY</span><strong>{game.awayTeam}</strong><small>{game.awayRecord||"Current matchup context"}</small></div><div><span>HOME</span><strong>{game.homeTeam}</strong><small>{game.homeRecord||"Current matchup context"}</small></div></div><div className={styles.contextLine}><b>Matchup:</b> {game.state==="in"?`Live · ${game.status}`:game.state==="post"?"Final":`${timeLabel(game.date)} · ${game.venue||"Venue TBD"}`}</div></section>
  <section className={styles.intelBlock}><div className={styles.blockHead}><h3>⭐ Key Players / Top Prop Rankings</h3><div className={styles.teamPills}><button className={teamFilter==="all"?styles.activePill:""} onClick={()=>setTeamFilter("all")}>All</button><button className={teamFilter==="away"?styles.activePill:""} onClick={()=>setTeamFilter("away")}>{game.awayAbbr}</button><button className={teamFilter==="home"?styles.activePill:""} onClick={()=>setTeamFilter("home")}>{game.homeAbbr}</button></div></div>{loading?<div className={styles.loading}>Loading game intelligence…</div>:null}{!loading&&!filtered.length?<div className={styles.loading}>No ranked player props are currently attached to this matchup.</div>:null}<div className={styles.rankTable}>{filtered.map((row,i)=><Link href={playerHref(sport,row,game)} key={`${row.market}-${row.playerId}-${i}`} className={styles.rankRow}><span className={styles.rankNo}>#{row.rank||i+1}</span><span className={styles.rankPlayer}><b>{row.playerName||"Player"}</b><small>{row.teamName||""} · {row.marketLabel||row.market}</small></span><span className={styles.rankLine}>{row.sportsbookLine==null?"Line —":`O/U ${row.sportsbookLine}`}</span><span className={styles.rankProjection}>{row.modelProjection==null?"Proj —":`Proj ${Number(row.modelProjection).toFixed(1)}`}</span><span className={styles.rankGi}>GI {row.giScore==null?"—":Number(row.giScore).toFixed(1)}</span><span className={styles.rankArrow}>›</span></Link>)}</div></section>
  <section className={styles.intelBlock}><div className={styles.blockHead}><h3>👥 Player Roster</h3><div className={styles.teamPills}><button className={rosterSide==="away"?styles.activePill:""} onClick={()=>{setRosterSide("away");setShowFull(false)}}>{game.awayAbbr}</button><button className={rosterSide==="home"?styles.activePill:""} onClick={()=>{setRosterSide("home");setShowFull(false)}}>{game.homeAbbr}</button></div></div>{!active?.players?.length&&!loading?<div className={styles.loading}>Roster data is not available yet for this matchup.</div>:null}<div className={styles.rosterList}>{visible.map(p=><Link href={rosterPlayerHref(sport,p,active,game)} key={p.playerId} className={styles.rosterRow}>{p.headshot?<img src={p.headshot} alt=""/>:<span className={styles.rosterFallback}>{initials(p.playerName)}</span>}<span><b>{p.playerName}</b><small>{p.position||"Player"}{p.starter?" · Starter":""}{!p.active?" · Inactive":""}</small></span><i>›</i></Link>)}</div>{active?.players?.length>12?<button className={styles.fullRosterButton} onClick={()=>setShowFull(v=>!v)}>{showFull?"Show Key Roster":`View Full ${active.teamAbbr||"Team"} Roster`}</button>:null}</section>
 </div>
}

export function GameSlatePage({sport,league="eng.1"}:{sport:GameSlateSport;league?:string}){
 const[games,setGames]=useState<Game[]>([]),[open,setOpen]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;let c:AbortController|null=null;const load=()=>{c?.abort();c=new AbortController();const p=new URLSearchParams({sport,league});fetch(`/api/game-slate?${p.toString()}`,{cache:"no-store",signal:c.signal}).then(r=>r.json()).then(payload=>{if(!alive)return;setGames(Array.isArray(payload?.games)?payload.games:[]);setError(payload?.success===false?payload?.error||"Game slate unavailable.":"");setLoading(false)}).catch(()=>{if(!alive||c?.signal.aborted)return;setError("Game slate is temporarily unavailable.");setLoading(false)})};load();const t=window.setInterval(load,30000);return()=>{alive=false;c?.abort();window.clearInterval(t)}},[sport,league]);
 const grouped=useMemo(()=>{const m=new Map<string,Game[]>();for(const g of games){const k=localDay(g.date)||"upcoming";m.set(k,[...(m.get(k)||[]),g])}return[...m.entries()].sort(([a],[b])=>a.localeCompare(b))},[games]);
 return<main className={styles.shell}><div className={styles.goldWash} aria-hidden="true"/><BrandHeader sport={sport}/><div className={styles.utilityRow}><Link href={`/${sport}`} className={styles.backButton}>← Back to {LABELS[sport]}</Link><span>{ICONS[sport]} {LABELS[sport]} Intelligence</span></div><section className={styles.hero}><span>{LABELS[sport]} INTELLIGENCE</span><h1>{LABELS[sport]} Game Slate</h1><p>Matchups · team context · player rankings · clickable rosters · live game status</p></section>{loading?<div className={styles.state}>Loading game slate…</div>:null}{error?<div className={styles.state}>{error}</div>:null}{!loading&&!error&&!games.length?<div className={styles.state}>No games are currently available in this slate window.</div>:null}{grouped.map(([dateKey,dateGames])=><section className={styles.daySection} key={dateKey}><div className={styles.dayHead}><h2>{dateGames[0]?.date?dayLabel(dateGames[0].date):"Upcoming Games"}</h2><span>{dateGames.length} game{dateGames.length===1?"":"s"}</span></div><div className={styles.games}>{dateGames.map(game=>{const expanded=open===game.id,live=game.state==="in",final=game.state==="post";return<article className={`${styles.gameCard} ${live?styles.liveCard:""} ${expanded?styles.openCard:""}`} key={game.id}><div className={styles.gameMeta}><strong className={live?styles.liveText:""}>{live?`LIVE · ${game.status||"In Progress"}`:final?"FINAL":timeLabel(game.date)}</strong><span>{game.venue||(final?"Game complete":"Matchup")}</span></div><div className={styles.matchup}><div className={styles.team}><TeamLogo src={game.awayLogo} name={game.awayTeam}/><div><b>{game.awayTeam}</b><small>{game.awayRecord||game.awayAbbr}</small></div>{game.state!=="pre"?<strong>{game.awayScore??"—"}</strong>:null}</div><div className={styles.versus}>@</div><div className={styles.team}><TeamLogo src={game.homeLogo} name={game.homeTeam}/><div><b>{game.homeTeam}</b><small>{game.homeRecord||game.homeAbbr}</small></div>{game.state!=="pre"?<strong>{game.homeScore??"—"}</strong>:null}</div></div><button className={styles.expandButton} onClick={()=>setOpen(expanded?"":game.id)} aria-expanded={expanded}>{expanded?"Hide Game Intelligence":"View Game Intelligence"}<span>{expanded?"⌃":"›"}</span></button>{expanded?<ExpandedGame sport={sport} league={league} game={game}/>:null}</article>})}</div></section>)}</main>
}
