"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BATTER_MARKETS, PITCHER_MARKETS, playerHeadshot, rankingName, rankingPlayerId, numberValue, percentValue, type RankingRow } from "@/lib/mlb";

type ScheduleResponse = { success:boolean; games:any[]; fetchedAt?:string; lineupsConfirmed?:number; error?:string };
type RankingResponse = { success:boolean; batter:Record<string,RankingRow[]>; pitcher:Record<string,RankingRow[]>; connected:boolean; errors?:string[]; updatedAt?:string; dataDate?:string };
type PerformanceResponse = { success:boolean; connected:boolean; batter:any; pitcher:any; emerging:any; hrIntelligence?:{live?:any[];yesterdayWatch?:any[];yesterday?:any[];emergingToday?:any[]}; errors?:string[] };

function useJson<T>(url:string,fallback:T){const[data,setData]=useState<T>(fallback);const[loading,setLoading]=useState(true);useEffect(()=>{let live=true;const load=()=>fetch(url,{cache:"no-store"}).then(r=>r.json()).then(v=>live&&setData(v)).catch(()=>{}).finally(()=>live&&setLoading(false));load();const id=setInterval(load,30000);return()=>{live=false;clearInterval(id)}},[url]);return{data,loading}}
function historyRows(payload:any){return Object.entries(payload?.days||{}).sort(([a],[b])=>String(b).localeCompare(String(a)))}
function torontoDate(offset=0){const d=new Date(Date.now()+offset*86400000);const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Toronto",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const g=(t:string)=>parts.find(x=>x.type===t)?.value||"";return `${g("year")}-${g("month")}-${g("day")}`}
function includeDate(date:string,period:string){const today=torontoDate(),yesterday=torontoDate(-1);if(period==="Today")return date===today;if(period==="Yesterday")return date===yesterday;const d=new Date(`${date}T12:00:00Z`),t=new Date(`${today}T12:00:00Z`);const diff=Math.round((+t-+d)/86400000);if(period==="Week")return diff>=0&&diff<7;if(period==="Month")return date.slice(0,7)===today.slice(0,7);return date.slice(0,4)===today.slice(0,4)}
function aggregate(payload:any,period:string,category?:string){let settled=0,correct=0,pending=0,total=0,absError=0;for(const[date,day]of historyRows(payload) as any[]){if(!includeDate(String(date),period))continue;const cats=day?.categories||{};const lists=category?[cats?.[category]]:Object.values(cats);for(const cat of lists as any[])for(const row of(Array.isArray(cat)?cat:[])){total++;if(typeof row?.correct==="boolean"){settled++;if(row.correct)correct++;continue}if(row?.finalized===true&&typeof row?.absolute_error==="number"){settled++;absError+=Number(row.absolute_error||0);if(Number(row.absolute_error)<=1)correct++;continue}pending++;}}return{settled,correct,pending,total,hitRate:settled?(correct/settled*100).toFixed(1):"0.0",avgError:settled?(absError/settled).toFixed(2):"0.00"}}


function teamShort(name:string){const m:any={"Arizona Diamondbacks":"ARI","Atlanta Braves":"ATL","Baltimore Orioles":"BAL","Boston Red Sox":"BOS","Chicago Cubs":"CHC","Chicago White Sox":"CWS","Cincinnati Reds":"CIN","Cleveland Guardians":"CLE","Colorado Rockies":"COL","Detroit Tigers":"DET","Houston Astros":"HOU","Kansas City Royals":"KC","Los Angeles Angels":"LAA","Los Angeles Dodgers":"LAD","Miami Marlins":"MIA","Milwaukee Brewers":"MIL","Minnesota Twins":"MIN","New York Mets":"NYM","New York Yankees":"NYY","Athletics":"ATH","Philadelphia Phillies":"PHI","Pittsburgh Pirates":"PIT","San Diego Padres":"SD","San Francisco Giants":"SF","Seattle Mariners":"SEA","St. Louis Cardinals":"STL","Tampa Bay Rays":"TB","Texas Rangers":"TEX","Toronto Blue Jays":"TOR","Washington Nationals":"WSH"};return m[name]||name}
function contactText(r:any){const barrel=Number(r?.barrel_count||0),hard=Number(r?.hard_hit_count||0),ev=Number(r?.best_exit_velocity||0),ang=r?.best_launch_angle;const lead=barrel>0?`🔥 ${barrel} Barrel${barrel===1?"":"s"}`:`💥 ${hard} Hard Hit${hard===1?"":"s"}`;return `${lead} · Best ${ev?ev.toFixed(1):"—"} mph${ang==null?"":` · ${Number(ang).toFixed(0)}°`}`}
function HrSignalRows({rows,showRank=false,prefix=""}:{rows:any[];showRank?:boolean;prefix?:string}){return <div className="hrSignalRows">{rows.map((r:any,i:number)=><div className="hrSignalRow" key={`${r.player_id||r.player_name}-${i}`}><strong>{r.player_name||"Player"}</strong><span> · {prefix}{teamShort(String(r.away_team_name||"Away"))} @ {teamShort(String(r.home_team_name||"Home"))}{showRank&&r.hr_rank?` · HR #${r.hr_rank}`:""}</span><span> | {contactText(r)}</span></div>)}</div>}

function RankingCard({row,pitcher=false}:{row:RankingRow;pitcher?:boolean}){
  const [open,setOpen]=useState(false);
  const id=rankingPlayerId(row),name=rankingName(row),image=String(row.headshot_url||playerHeadshot(id));
  const gi=numberValue(row.gi_score,1), team=String(row.team_abbreviation||row.team_name||"MLB"),opp=String(row.opponent_abbreviation||row.opponent_name||"");
  const teamId=Number((row as any).team_id||(row as any).teamId||0);
  const logo=teamId?`https://www.mlbstatic.com/team-logos/${teamId}.svg`:String((row as any).team_logo_url||"");
  const probability=percentValue(row.hr_probability??row.probability),projection=numberValue(row.projection,1),pitcherName=String(row.opposing_probable_pitcher||row.probable_pitcher||"");
  const confirmed=row.lineup_confirmed!==false;
  const summary=String((row as any).summary||(row as any).reason||(row as any).intelligence_summary||(pitcher?"Ranked by workload, season rates, matchup and sample reliability.":"GI score blends performance, matchup, lineup position, park/weather and sample reliability."));
  const evidence=String((row as any).performance_evidence||(row as any).market_evidence||(row as any).recent_form||summary);
  const why=String((row as any).why_this_player||(row as any).ranking_reason||(row as any).why_ranked||summary);
  const statcast=String((row as any).statcast_summary||(row as any).contact_quality||(row as any).contact_summary||"");
  return <article className={`origRankCard ${pitcher?"pitcher":"batter"} ${open?"expanded":""}`}>
    <div className="origRank">#{Number(row.rank||0)||"—"}<span>−</span></div>
    <div className="origPhotoWrap"><img className="origHeadshot" src={image} alt=""/>{logo?<img className="origTeamLogo" src={logo} alt=""/>:null}</div>
    <div className="origRankBody"><strong className="origName">{name}</strong><div className="origMatch">{team}{opp?` vs. ${opp}`:""}</div>
      {pitcher?<><div className="origProp"><b>Projection:</b> {projection} K</div></>:<><div className="origProp">{pitcherName?<>vs. <b>{pitcherName}</b></>:null}</div><div className="origProp"><b>HR Probability:</b> {probability}</div></>}
      <p>{summary}</p>
      <span className="confirmed">✓ {confirmed?"Confirmed lineup":"Lineup Pending"}{row.batting_order?` · #${row.batting_order}`:""}</span>
    </div>
    <div className="origGi"><small>GI SCORE</small><strong>{gi}</strong></div>
    <button className="origIntel" onClick={()=>setOpen(v=>!v)}>ⓘ {open?"Close Intelligence":"View Intelligence"}</button>
    {open?<div className="origInlineIntel">
      <div className="intelKpis"><article><span>GI Score</span><strong>{gi}</strong></article><article><span>{pitcher?"Projection":"Probability"}</span><strong>{pitcher?`${projection} K`:probability}</strong></article><article><span>Lineup</span><strong>{confirmed?"Confirmed":"Pending"}</strong></article></div>
      <details><summary>› Market Performance Evidence</summary><p>{evidence}</p></details>
      {!pitcher&&statcast?<details><summary>› Statcast Contact Quality</summary><p>{statcast}</p></details>:null}
      <details><summary>› Why This {pitcher?"Pitcher":"Player"} Ranks Here</summary><p>{why}</p></details>
      {id?<Link className="openFullCard" href={`/mlb/player/${id}?gi=${encodeURIComponent(gi)}&team=${encodeURIComponent(team)}&opp=${encodeURIComponent(opp)}&matchup=${encodeURIComponent(pitcherName)}&rank=${encodeURIComponent(String(row.rank||""))}&prob=${encodeURIComponent(probability)}&order=${encodeURIComponent(String(row.batting_order||""))}`}>Open full player card</Link>:null}
    </div>:null}
  </article>
}

export function MlbDashboard(){
  const schedule=useJson<ScheduleResponse>("/api/mlb/schedule",{success:false,games:[]});
  const rankings=useJson<RankingResponse>("/api/mlb/rankings",{success:false,batter:{},pitcher:{},connected:false});
  const performance=useJson<PerformanceResponse>("/api/mlb/performance",{success:false,connected:false,batter:{},pitcher:{},emerging:{}});
  const[role,setRole]=useState<"Batter"|"Pitcher">("Batter"),[market,setMarket]=useState("home_runs"),[period,setPeriod]=useState("Today"),[perfRole,setPerfRole]=useState<"Batter"|"Pitcher"|"Emerging Power">("Batter"),[hrTab,setHrTab]=useState<"Live HR"|"Yesterday"|"Emerging Power">("Live HR"),[showOutside,setShowOutside]=useState(false),[showYesterdayMore,setShowYesterdayMore]=useState(false),[showEmergingMore,setShowEmergingMore]=useState(false),[showFull,setShowFull]=useState(false),[perfMarket,setPerfMarket]=useState("home_runs");
  const games=schedule.data.games||[],liveGames=games.filter(g=>g.isLive),finalGames=games.filter(g=>g.isFinal),delayed=games.filter(g=>g.isDelayed).length;
  const perfPayload=perfRole==="Pitcher"?performance.data.pitcher:perfRole==="Emerging Power"?performance.data.emerging:performance.data.batter;
  const perf=useMemo(()=>aggregate(perfPayload,period),[perfPayload,period]);
  const perfMarketSummary=useMemo(()=>aggregate(perfPayload,period,perfRole==="Emerging Power"?"emerging_power":perfMarket),[perfPayload,period,perfRole,perfMarket]);
  const marketList=role==="Batter"?BATTER_MARKETS:PITCHER_MARKETS;
  useEffect(()=>{if(role==="Batter"&&!BATTER_MARKETS.some(x=>x[0]===market))setMarket("home_runs");if(role==="Pitcher"&&!PITCHER_MARKETS.some(x=>x[0]===market))setMarket("strikeouts")},[role,market]);
  useEffect(()=>{setPerfMarket(perfRole==="Pitcher"?"strikeouts":"home_runs")},[perfRole]);
  useEffect(()=>setShowFull(false),[role,market]);
  const rows=(role==="Batter"?rankings.data.batter?.[market]:rankings.data.pitcher?.[market])||[],activeMarket=marketList.find(x=>x[0]===market)||marketList[0];
  const updated=rankings.data.updatedAt?new Date(rankings.data.updatedAt).toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"}):"Live";

  return <div className="origMlb">
    <section className="origHero"><h1>MLB Intelligence Center</h1><p>Start with the strongest players in each market, review the reason behind every ranking, and open the full Top 25 only when you need more depth.</p></section>
    <div className="origUpdated">Last updated {updated}</div>

    <Link className="origGamesEntry" href="/mlb/games"><strong>⚾ TODAY&apos;S MLB GAMES</strong><span>Open today&apos;s slate, lineups &amp; Game Intelligence ›</span></Link>
    <section className="origSnapshot"><div className="snapshotTitleRow"><h2>Today&apos;s MLB Snapshot</h2><p>Always confirm starting lineups</p></div><div className="origMetrics snapshot"><article className="green"><span>GAMES</span><strong>{schedule.loading?"…":games.length}</strong><small>{liveGames.length} live · {finalGames.length} final</small></article><article><span>LINEUPS</span><strong>{schedule.data.lineupsConfirmed!=null?`${schedule.data.lineupsConfirmed}/${Math.max(games.length*2,0)}`:"—"}</strong><small>Confirmed</small></article><article className="gold"><span>ALERTS</span><strong>{delayed}</strong><small>{delayed?"Delayed / suspended":"No active alerts"}</small></article></div></section>

    <section className="origSection hr"><h2>🔥 HR Intelligence</h2><div className="origTabs three boxedHrTabs">{(["Live HR","Yesterday","Emerging Power"] as const).map(x=><button key={x} className={hrTab===x?"active":""} onClick={()=>setHrTab(x)}>{x}</button>)}</div>
      {hrTab==="Live HR"&&<div className="hrPane"><h3>Live hard-contact signals</h3><p className="hrCaption">Live hard-contact signals from all hitters in games currently in progress. Barrels and 95+ mph hard-hit balls are context signals, not guarantees.</p><details><summary>›　ⓘ What do the HR contact signals mean?</summary><div className="origExplain"><p><b>🔥 Barrel</b> — a batted ball with a strong combination of exit velocity and launch angle associated with extra-base damage and home-run potential.</p><p><b>💥 Hard Hit</b> — a batted ball hit at <b>95 mph or harder</b> that does not necessarily qualify as a barrel.</p><p><b>mph / Exit Velocity</b> — how fast the ball leaves the bat. Higher is generally stronger contact.</p><p><b>° / Launch Angle</b> — the vertical angle at which the ball leaves the bat.</p><p><b>Important:</b> a barrel or hard hit is a contact-quality signal, <b>not a prediction or guarantee</b> that the player will hit a home run.</p></div></details><details><summary>›　ⓘ What should I look for in an HR pick?</summary><div className="origExplain"><p><b>Start with barrel rate:</b> below 7% is low, 7–9.9% is average, 10–14.9% is strong, and 15%+ is elite HR contact.</p><p><b>Then confirm the full picture:</b> strong xSLG and recent barrels, a vulnerable opposing pitcher, favourable handedness, a hitter-friendly park or weather edge, and a confirmed top-five lineup position.</p></div></details>
        {(()=>{const all=performance.data.hrIntelligence?.live||[],top=all.filter((r:any)=>r.hr_rank),outside=all.filter((r:any)=>!r.hr_rank);return all.length?<><h4>⭐ HR TOP 25</h4>{top.length?<HrSignalRows rows={top.slice(0,3)} showRank/>:<p className="hrNone">None right now.</p>}{top.length>3?<details className="hrMore"><summary>Show {top.length-3} more Top 25 signals</summary><HrSignalRows rows={top.slice(3)} showRank/></details>:null}<h4>🆕 OUTSIDE HR TOP 25</h4>{outside.length?<HrSignalRows rows={outside.slice(0,3)}/>:<p className="hrNone">None right now.</p>}{outside.length>3?<div><button className="hrMoreButton" onClick={()=>setShowOutside(v=>!v)}>›　{showOutside?"Hide outside signals":`Show ${outside.length-3} more outside signals`}</button>{showOutside?<HrSignalRows rows={outside.slice(3)}/>:null}</div>:null}</>:<div className="origInfo">{liveGames.length?"No qualifying live hard-contact signals yet.":"No MLB games are currently live."}</div>})()}
      </div>}
      {hrTab==="Yesterday"&&<div className="hrPane"><h3>👀 Yesterday&apos;s Power Watch</h3><p className="hrCaption">Yesterday&apos;s strongest HR-shaped contact that stayed in the park: barrels or 100+ mph contact in a 15°–40° launch window, with all players who homered excluded. Context only — not a &apos;due&apos; signal.</p>{(()=>{const all=performance.data.hrIntelligence?.yesterdayWatch||[],top=all.filter((r:any)=>r.hr_rank),outside=all.filter((r:any)=>!r.hr_rank);return all.length?<><h4>⭐ ALSO IN TODAY&apos;S HR TOP 25</h4>{top.length?<HrSignalRows rows={top.slice(0,3)} showRank prefix="Yesterday "/>:<p className="hrNone">None.</p>}<h4>👀 OUTSIDE TODAY&apos;S HR TOP 25</h4>{outside.length?<HrSignalRows rows={outside.slice(0,3)} prefix="Yesterday "/>:<p className="hrNone">None.</p>}{outside.length>3?<div><button className="hrMoreButton" onClick={()=>setShowYesterdayMore(v=>!v)}>›　{showYesterdayMore?"Hide watch signals":`Show ${Math.min(outside.length,10)-3} more watch signals`}</button>{showYesterdayMore?<HrSignalRows rows={outside.slice(3,10)} prefix="Yesterday "/>:null}</div>:null}</>:<div className="origInfo">No qualifying no-HR hard-contact signals were found from yesterday.</div>})()}</div>}
      {hrTab==="Emerging Power"&&<div className="hrPane"><p className="emergingIntro">Surface low-HR / limited-sample hitters with evidence-backed upside.</p><h3>Emerging Power · low-HR &amp; limited-sample hitters</h3><p className="hrCaption">This view looks for players whose low season HR total may hide stronger underlying matchup/contact evidence. A player is never included simply because they are &apos;due&apos;.</p>{(()=>{const all=performance.data.hrIntelligence?.emergingToday||[];const render=(rows:any[])=><div className="emergingRows">{rows.map((r:any,i:number)=><article key={`${r.player_id||r.player_name}-${i}`}><div><strong>{r.player_name||r.player||"Player"}</strong><span> · {r.team_abbreviation||r.team_name||r.team||""}{r.opponent_abbreviation||r.opponent_name?` vs ${r.opponent_abbreviation||r.opponent_name}`:""}{r.current_year_debut||r.limited_sample?" · ROOKIE/LIMITED SAMPLE":""}</span></div><b>{Number(r.season_home_runs||0)} season HR · GI {numberValue(r.gi_score||r.score,1)}{Number(r.home_run_probability||r.hr_probability||r.probability||0)?` · ${Math.round(Number(r.home_run_probability||r.hr_probability||r.probability))}% HR`:""}</b><p>{r.explanation||"Underlying power indicators are being evaluated."}</p></article>)}</div>;return all.length?<>{render(all.slice(0,4))}{all.length>4?<div><button className="hrMoreButton" onClick={()=>setShowEmergingMore(v=>!v)}>⌄　{showEmergingMore?"Hide emerging-power signals":`Show ${all.length-4} more emerging-power signals`}</button>{showEmergingMore?render(all.slice(4)):null}</div>:null}</>:<div className="origInfo">No evidence-backed emerging-power signals qualify right now.</div>})()}</div>}
    </section>

    <section className="origSection performance"><h2>📊 Prediction Performance</h2><details><summary>ⓘ How performance is measured</summary><div className="origExplain"><p>Settled predictions are graded against the recorded MLB result. Pending predictions are excluded from hit rate until they settle.</p></div></details>
      <div className="origTabs three">{(["Batter","Pitcher","Emerging Power"] as const).map(x=><button key={x} className={perfRole===x?"active":""} onClick={()=>setPerfRole(x)}>{x==="Batter"?"🥎 ":x==="Pitcher"?"⚾ ":"🔥 "}{x}</button>)}</div>
      <h3>🌐 Overall MLB {perfRole} Performance</h3><div className="origPeriods">{["Today","Yesterday","Week","Month","Season"].map(x=><button key={x} className={period===x?"active":""} onClick={()=>setPeriod(x)}>{x}</button>)}</div>
      <div className="origMetrics"><article className="green"><span>{perfRole==="Pitcher"?"Within 1 / Graded":"Hits / Settled"}</span><strong>{perf.correct} / {perf.settled}</strong></article><article><span>{perfRole==="Pitcher"?"Graded":"Settled"}</span><strong>{perf.settled}</strong></article><article className="gold"><span>Pending</span><strong>{perf.pending}</strong></article></div>
      {perfRole!=="Emerging Power"?<><div className="origTabs markets perfMarkets">{(perfRole==="Pitcher"?PITCHER_MARKETS:BATTER_MARKETS).map(([key,icon,label])=><button key={key} className={perfMarket===key?"active":""} onClick={()=>setPerfMarket(key)}>{icon} {label}</button>)}</div><div className="perfMarketSummary"><strong>{(perfRole==="Pitcher"?PITCHER_MARKETS:BATTER_MARKETS).find(x=>x[0]===perfMarket)?.[2]}</strong><span>{perfRole==="Pitcher"?`Within 1 ${perfMarketSummary.correct} / ${perfMarketSummary.settled} · Avg error ${perfMarketSummary.avgError} · Pending ${perfMarketSummary.pending}`:`Hits ${perfMarketSummary.correct} / ${perfMarketSummary.settled} · Pending ${perfMarketSummary.pending}`}</span></div></>:null}
    </section>

    <section className="origSection rankings"><div className="origRankingsHeader"><h2>Player Rankings</h2><p>Market-specific intelligence · live matchup context</p></div>
      {!rankings.loading&&!rankings.data.connected?<div className="origDataNote"><b>Data connection required:</b> add the existing Supabase variables to this Railway service. The page will populate automatically after redeploy.</div>:null}
      <div className="origTabs two"><button className={role==="Batter"?"active":""} onClick={()=>setRole("Batter")}>🥎 Batter</button><button className={role==="Pitcher"?"active":""} onClick={()=>setRole("Pitcher")}>⚾ Pitcher</button></div>
      <div className="origTabs markets">{marketList.map(([key,icon,label])=><button key={key} className={market===key?"active":""} onClick={()=>setMarket(key)}>{icon} {label}</button>)}</div>
      <div className="origMarketHead"><h2>{activeMarket[1]} {activeMarket[2]}{role==="Batter"?" Rankings":""}</h2><p>{role==="Batter"?"Ranked by GI Score. Probability is one component of the score, alongside player performance, matchup, lineup position, ballpark, weather, and sample reliability.":"Ranked by pitcher GI score using workload, season rates, sample reliability, matchup and opponent handedness."}</p></div>
      <div className="origCards">{rows.slice(0,showFull?25:5).map((row,i)=><RankingCard key={`${rankingPlayerId(row)}-${i}`} row={row} pitcher={role==="Pitcher"}/>)}{!rankings.loading&&rows.length===0?<div className="origEmpty">No completed {activeMarket[2]} snapshot is available yet.</div>:null}</div>{rows.length>5?<button className="viewFullTop25" onClick={()=>setShowFull(v=>!v)}>{showFull?"Show Top 5 Only":"View Full Top 25"}</button>:null}
    </section>
  </div>
}
