"use client";
import {useEffect,useMemo,useState} from "react";
import type {NflMarketKey} from "@/lib/nfl";
type P={season:number;gameId:string;date:string;opponent:string;atVs:string;value:number};
type R={success:boolean;supported:boolean;points:P[];statLabel:string;message?:string};
function date(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?(v||"—"):new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",month:"2-digit",day:"2-digit",year:"2-digit"}).format(d)}
export function NflPlayerHistory({playerId,playerName,market,marketLabel,line}:{playerId:string;playerName:string;market:NflMarketKey;marketLabel:string;line:string}){
 const[span,setSpan]=useState<5|10|20>(10); const[data,setData]=useState<R|null>(null);
 useEffect(()=>{let on=true;setData(null);fetch(`/api/nfl/player/${encodeURIComponent(playerId)}/history?market=${encodeURIComponent(market)}`,{cache:"no-store"}).then(r=>r.json()).then(v=>on&&setData(v)).catch(()=>on&&setData({success:false,supported:true,points:[],statLabel:marketLabel,message:"Player history is temporarily unavailable."}));return()=>{on=false}},[playerId,market,marketLabel]);
 const pts=useMemo(()=>(data?.points||[]).slice(-span),[data,span]); const ln=Number(line),has=Number.isFinite(ln);
 const max=Math.max(1,has?ln:0,...pts.map(x=>x.value)); const avg=(x:P[])=>x.length?(x.reduce((a,b)=>a+b.value,0)/x.length).toFixed(1):"—";
 const hits=has?pts.filter(x=>x.value>ln).length:0;
 return <section className="hb"><div className="tabs">{([5,10,20] as const).map(n=><button key={n} className={span===n?"active":""} onClick={()=>setSpan(n)}>Last {n}</button>)}</div>
 <h2>Last {span} Games · {marketLabel}</h2>
 {!data?<div className="empty">Loading player history…</div>:!data.supported?<div className="empty">{data.message}</div>:!pts.length?<div className="empty">{data.message||`No verified ${marketLabel.toLowerCase()} history is available for ${playerName}.`}</div>:<>
 <div className="chart">{has?<div className="line" style={{bottom:`${Math.max(8,Math.min(128,(ln/max)*120+8))}px`}}><span>Line {ln}</span></div>:null}
 {pts.map((p,i)=><div className="col" key={`${p.gameId}-${i}`}><b>{p.value}</b><div className="track"><i style={{height:`${Math.max(5,(p.value/max)*120)}px`}}/></div><span>{date(p.date)}</span><small>{p.opponent||p.season}</small></div>)}</div>
 <div className="stats"><article><small>L5 AVG</small><strong>{avg(pts.slice(-5))}</strong></article><article><small>L10 AVG</small><strong>{avg(pts.slice(-10))}</strong></article><article><small>{has?"OVER LINE":"GAMES"}</small><strong>{has?`${hits}/${pts.length}`:pts.length}</strong></article></div>
 {pts.some(p=>p.season<2026)?<p className="note">2025 history is included for returning players until the 2026 sample is large enough.</p>:null}</>}
 <style jsx>{`.hb{margin-top:20px}.tabs{display:flex;border-bottom:2px solid #34373d;overflow-x:auto}.tabs button{flex:1;min-width:100px;background:#111319;color:#fff;border:1px solid #383b42;padding:12px;font-weight:800}.tabs button.active{border-color:#f04f5f;background:#351015}h2{font-size:24px;margin:18px 0 12px}.chart{position:relative;display:flex;align-items:flex-end;gap:8px;overflow-x:auto;padding:18px 10px 8px;border:1px solid #34373d;border-radius:16px;background:#0d0f10;min-height:190px}.line{position:absolute;left:0;right:0;border-top:1px dashed #d9b85d;z-index:1}.line span{position:absolute;right:6px;top:-18px;color:#d9b85d;font-size:10px}.col{min-width:54px;display:grid;grid-template-rows:22px 124px auto auto;justify-items:center;align-items:end;z-index:2}.col b{font-size:12px}.track{height:124px;display:flex;align-items:flex-end}.track i{display:block;width:18px;border-radius:6px 6px 2px 2px;background:#20df7f}.col span{margin-top:6px;color:#d5d6d9;font-size:10px;white-space:nowrap}.col small{color:#8f949c;font-size:9px;max-width:65px;text-align:center}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.stats article{border:1px solid #34373d;border-left:4px solid #20df7f;border-radius:12px;padding:10px;background:#111214}.stats small{display:block;color:#9da1a8;font-size:10px}.stats strong{display:block;margin-top:5px;font-size:18px}.empty{border:1px solid #34373d;border-radius:14px;padding:18px;color:#a9acb3;background:#0d0f10}.note{color:#9da1a8;font-size:13px}@media(max-width:600px){.stats{grid-template-columns:repeat(3,1fr)}.col{min-width:49px}}`}</style></section>
}
