"use client";
/* eslint-disable @next/next/no-img-element -- ESPN provides dynamic external image URLs. */
import { useState } from "react";
import { WNBA_MARKETS, wnbaHeadshot } from "@/lib/wnba";
import type { WnbaGame, WnbaMarket, WnbaOverview, WnbaRanking } from "@/lib/wnba";

const sections=["Intelligence","Games","Player Props","Performance"] as const;
type Section=(typeof sections)[number];
const num=(value:number|null,digits=1)=>value===null?"—":value.toFixed(digits);
function dateLabel(value:string|null){if(!value)return"Time TBD";return new Intl.DateTimeFormat("en-CA",{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Toronto",timeZoneName:"short"}).format(new Date(value))}

function PlayerCard({player,onOpen}:{player:WnbaRanking;onOpen:()=>void}){return <article className="rankingCard"><div className="rankNumber">#{player.rank}</div><img className="playerPhoto" src={wnbaHeadshot(player.playerId)} alt=""/><div className="rankingCopy"><h3>{player.playerName}</h3><p>{player.team} · 2026 regular season</p><strong>{player.market} · {player.metricLabel} {num(player.rankingValue)}</strong></div><div className="rankingMetrics"><span><small>{player.metricLabel}</small><b>{num(player.rankingValue)}</b></span><span><small>GAMES</small><b>{num(player.gamesPlayed,0)}</b></span><span><small>MIN/G</small><b>{num(player.minutesPerGame)}</b></span></div><button className="intelligenceButton" onClick={onOpen}>View Intelligence</button></article>}

function Games({games}:{games:WnbaGame[]}){if(!games.length)return <div className="emptyState">No WNBA games were returned for this window.</div>;return <div className="gameList">{games.map(game=>{const showScore=game.state==="in"||game.state==="post";return <article className="gameCard" key={game.gameId}><div className="gameTop"><span>{dateLabel(game.tipoff)}</span><b>{game.status}</b></div>{(["away","home"] as const).map(side=>{const name=side==="away"?game.awayTeam:game.homeTeam,abbr=side==="away"?game.awayAbbr:game.homeAbbr,logo=side==="away"?game.awayLogo:game.homeLogo,score=side==="away"?game.awayScore:game.homeScore;return <div className="teamRow" key={side}>{logo?<img src={logo} alt=""/>:<span/>}<div><strong>{name}{showScore&&score!==null?` · ${score}`:""}</strong><small>{abbr}</small></div></div>})}</article>})}</div>}

function PlayerPanel({player,onClose}:{player:WnbaRanking;onClose:()=>void}){const metrics:[[string,number|null],[string,number|null],[string,number|null],[string,number|null],[string,number|null],[string,number|null],[string,number|null],[string,number|null]]=[["PTS/G",player.pointsPerGame],["REB/G",player.reboundsPerGame],["AST/G",player.assistsPerGame],["3PM/G",player.threesPerGame],["STL/G",player.stealsPerGame],["BLK/G",player.blocksPerGame],["MIN/G",player.minutesPerGame],["GAMES",player.gamesPlayed]];return <div className="playerOverlay" role="dialog" aria-modal="true"><button className="overlayBackdrop" aria-label="Close" onClick={onClose}/><section className="playerPanel"><button className="closeButton" onClick={onClose}>Close ×</button><div className="playerPanelHead"><img src={wnbaHeadshot(player.playerId)} alt=""/><div><p>{player.team} · 2026 regular season</p><h2>{player.playerName}</h2><strong>#{player.rank} in {player.market}</strong></div></div><div className="playerStatGrid">{metrics.map(([label,value])=><span key={label}><small>{label}</small><b>{num(value,label==="GAMES"?0:1)}</b></span>)}</div><div className="intelligenceCopy"><h3>Today’s Intelligence</h3><p><b>Market position:</b> {player.playerName} ranks #{player.rank} in {player.market} from the verified 2026 regular-season baseline at {num(player.rankingValue)} {player.metricLabel}.</p><p><b>Data boundary:</b> Sportsbook line, opponent edge, probability and GI score will be added only when verified live inputs are connected.</p></div></section></div>}

export function WnbaDashboard({data}:{data:WnbaOverview}){
 const [section,setSection]=useState<Section>("Intelligence"),[market,setMarket]=useState<WnbaMarket>("Points"),[showAll,setShowAll]=useState(false),[selected,setSelected]=useState<WnbaRanking|null>(null);
 const rows=data.rankings[market]??[],visible=showAll?rows:rows.slice(0,5);
 const dateFormat=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Toronto"}),today=dateFormat.format(new Date()),todaysGames=data.games.filter(g=>g.tipoff&&dateFormat.format(new Date(g.tipoff))===today);
 return <><nav className="tabBar wnbaTabs" aria-label="WNBA sections">{sections.map(item=><button className={section===item?"selected":""} key={item} onClick={()=>setSection(item)}>{item}</button>)}</nav>{data.warnings.map(w=><div className="dataWarning" key={w}>{w}</div>)}
 {section==="Intelligence"&&<><section className="wnbaSnapshot"><span><small>TODAY’S GAMES</small><b>{todaysGames.length}</b><em>{todaysGames.filter(g=>g.state==="in").length} live</em></span><span><small>UPCOMING</small><b>{data.games.filter(g=>g.state==="pre").length}</b><em>next 14 days</em></span><span><small>SEASON</small><b>{data.season}</b><em>regular season</em></span></section><section className="migrationStatus"><strong>Real WNBA data connected</strong><p>This website now reads the WNBA schedule and verified player statistics independently from the live dashboard.</p></section><div className="sectionTitle"><div><p>WNBA Intelligence</p><h2>Top Points Rankings</h2></div><button onClick={()=>setSection("Player Props")}>View all markets →</button></div><div className="rankingList">{data.rankings.Points.slice(0,5).map(p=><PlayerCard player={p} key={p.playerId} onOpen={()=>setSelected(p)}/>)}</div></>}
 {section==="Games"&&<section className="contentSection"><div className="sectionTitle"><div><p>WNBA Schedule</p><h2>Current game window</h2></div><span>{data.games.length} games</span></div><Games games={data.games}/></section>}
 {section==="Player Props"&&<section className="contentSection"><div className="sectionTitle"><div><p>Player Props</p><h2>Top 25 Rankings</h2></div><span>Verified season evidence</span></div><div className="marketSelector">{WNBA_MARKETS.map(item=><button className={market===item?"active":""} key={item} onClick={()=>{setMarket(item);setShowAll(false)}}>{item}</button>)}</div><div className="rankingList">{visible.map(p=><PlayerCard player={p} key={p.playerId} onOpen={()=>setSelected(p)}/>)}</div>{!visible.length&&<div className="emptyState">No qualified players are available for this market right now.</div>}{rows.length>5&&<button className="showRankings" onClick={()=>setShowAll(v=>!v)}>{showAll?"Show Top 5":"Open full Top 25"}</button>}</section>}
 {section==="Performance"&&<section className="contentSection"><div className="sectionTitle"><div><p>Prediction Results</p><h2>WNBA Performance</h2></div></div><div className="performanceNotice"><strong>Performance history is the next connection.</strong><p>No results are being fabricated. Saved WNBA prop predictions will appear here after the shared history store is connected.</p></div></section>}
 {selected&&<PlayerPanel player={selected} onClose={()=>setSelected(null)}/>}</>
}
