"use client";
import {useEffect,useMemo,useState} from "react";
import type {WnbaMarketKey} from "@/lib/wnba";
type P={season:number;gameId:string;date:string;opponent:string;atVs:string;value:number};
type R={success:boolean;supported:boolean;points:P[];statLabel:string;message?:string};
function date(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?(v||"—"):new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",month:"2-digit",day:"2-digit",year:"2-digit"}).format(d)}
function opp(v:string){const words=String(v||"").replace(/[^A-Za-z ]/g," ").split(/\s+/).filter(Boolean);return words.length?words.map(x=>x[0]).join("").slice(0,4).toUpperCase():"OPP"}
export function WnbaPlayerHistory({playerId,playerName,market,marketLabel,line}:{playerId:string;playerName:string;market:WnbaMarketKey;marketLabel:string;line:string}){
 const[span,setSpan]=useState<5|10|20>(10);const[data,setData]=useState<R|null>(null);const[selected,setSelected]=useState<P|null>(null);
 useEffect(()=>{let on=true;setData(null);setSelected(null);fetch(`/api/wnba/player/${encodeURIComponent(playerId)}/history?market=${encodeURIComponent(market)}`,{cache:"no-store"}).then(r=>r.json()).then(v=>on&&setData(v)).catch(()=>on&&setData({success:false,supported:true,points:[],statLabel:marketLabel,message:"Player history is temporarily unavailable."}));return()=>{on=false}},[playerId,market,marketLabel]);
 const pts=useMemo(()=>(data?.points||[]).slice(-span),[data,span]);const ln=Number(line),has=Number.isFinite(ln);const max=Math.max(1,has?ln:0,...pts.map(x=>x.value));const avg=(x:P[])=>x.length?(x.reduce((a,b)=>a+b.value,0)/x.length).toFixed(1):"—";const hits=has?pts.filter(x=>x.value>ln).length:0;
 return <section className="hb"><div className="tabs">{([5,10,20] as const).map(n=><button key={n} className={span===n?"active":""} onClick={()=>{setSpan(n);setSelected(null)}}>Last {n}</button>)}</div><h2>Last {span} Games · {marketLabel}</h2>
 {!data?<div className="empty">Loading player history…</div>:!data.supported?<div className="empty">{data.message}</div>:!pts.length?<div className="empty">{data.message||`No verified ${marketLabel.toLowerCase()} history is available for ${playerName}.`}</div>:<><div className="chart">{has?<div className="line" style={{bottom:`${Math.max(8,Math.min(112,(ln/max)*104+8))}px`}}><span>Line {ln}</span></div>:null}{pts.map((p,i)=><button className="col" key={`${p.gameId}-${i}`} onClick={()=>setSelected(p)} aria-label={`${date(p.date)} ${p.opponent} ${p.value}`}><b>{p.value}</b><div className="track"><i style={{height:`${Math.max(5,(p.value/max)*104)}px`}}/></div><span>{date(p.date)}</span><small>{opp(p.opponent)}</small></button>)}</div>{selected?<div className="tip"><button onClick={()=>setSelected(null)}>×</button><div><span>Date</span><b>{date(selected.date)}</b></div><div><span>Opponent</span><b>{selected.opponent||"—"}</b></div><div><span>{marketLabel}</span><b>{selected.value}</b></div></div>:null}<div className="stats"><article><small>L5 AVG</small><strong>{avg(pts.slice(-5))}</strong></article><article><small>L10 AVG</small><strong>{avg(pts.slice(-10))}</strong></article><article><small>{has?"OVER LINE":"GAMES"}</small><strong>{has?`${hits}/${pts.length}`:pts.length}</strong></article></div>{pts.some(p=>p.season<2026)?<p className="note">2025 history is included for returning players until the 2026 sample is large enough.</p>:null}</>}
 <style jsx>{`.hb{margin-top:15px}.tabs{display:flex;border-bottom:1.5px solid #34373d}.tabs button{flex:1;background:#111319;color:#fff;border:1px solid #383b42;padding:9px;font-weight:800;font-size:13px}.tabs button.active{border-color:#20df7f;background:#0d3523}h2{font-size:20px;margin:13px 0 9px}.chart{position:relative;display:flex;align-items:flex-end;gap:4px;overflow-x:auto;padding:14px 7px 7px;border:1px solid #34373d;border-radius:13px;background:#0d0f10;min-height:166px}.line{position:absolute;left:0;right:0;border-top:1px dashed #d9b85d;z-index:1}.line span{position:absolute;right:5px;top:-15px;color:#d9b85d;font-size:9px}.col{border:0;background:transparent;color:#fff;min-width:42px;display:grid;grid-template-rows:18px 108px auto auto;justify-items:center;align-items:end;z-index:2;padding:0}.col b{font-size:10px}.track{height:108px;display:flex;align-items:flex-end}.track i{display:block;width:15px;border-radius:5px 5px 2px 2px;background:#20df7f}.col span{margin-top:4px;color:#d5d6d9;font-size:8px;white-space:nowrap}.col small{color:#8f949c;font-size:8px}.tip{position:relative;display:grid;grid-template-columns:repeat(3,1fr);gap:7px;border:1px solid #4b4f55;border-radius:12px;background:#111319;padding:10px;margin-top:8px}.tip button{position:absolute;right:5px;top:3px;border:0;background:transparent;color:#aaa;font-size:18px}.tip span{display:block;color:#9da1a8;font-size:9px}.tip b{display:block;margin-top:3px;font-size:11px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.stats article{border:1px solid #34373d;border-left:3px solid #20df7f;border-radius:10px;padding:8px;background:#111214}.stats small{display:block;color:#9da1a8;font-size:9px}.stats strong{display:block;margin-top:3px;font-size:16px}.empty{border:1px solid #34373d;border-radius:12px;padding:14px;color:#a9acb3;background:#0d0f10}.note{color:#9da1a8;font-size:11px}@media(max-width:430px){.col{min-width:39px}.track i{width:13px}.tip{grid-template-columns:1fr}.tip b{font-size:12px}}`}</style></section>
}
