"use client";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import "./home-showcase.css";

type Game={id:string;date:string;awayAbbr:string;homeAbbr:string;awayLogo?:string|null;homeLogo?:string|null;awayRecord?:string;homeRecord?:string;state:"pre"|"in"|"post";status:string;awayScore?:string|number|null;homeScore?:string|number|null};
type Sport="nfl"|"cfb"|"nba"|"wnba"|"nhl";
type Item=Game&{sport:Sport};
type Prediction={sport:Sport;playerName:string;headshot?:string;market:string;line:number;gi:number;team?:string;status?:string};
function MetricIcon({kind}:{kind:"games"|"props"|"predictions"|"hit"}){const common={width:28,height:28,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(kind==="games")return <svg {...common}><rect x="3" y="6" width="18" height="12" rx="4"/><path d="M8 10v5M5.5 12.5h5M16.5 11h.01M19 14h.01"/></svg>;if(kind==="props")return <svg {...common}><circle cx="9" cy="8" r="3"/><path d="M2.5 20v-2a6.5 6.5 0 0 1 13 0v2M17 5a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3.5 5v1"/></svg>;if(kind==="predictions")return <svg {...common}><rect x="3" y="13" width="4" height="8" rx="1"/><rect x="10" y="8" width="4" height="13" rx="1"/><rect x="17" y="3" width="4" height="18" rx="1"/></svg>;return <svg {...common}><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1.4"/><path d="m12 12 7-7M17 5h2v2"/></svg>}
const SPORTS:{slug:Sport;name:string;icon:string}[]=[{slug:"nfl",name:"NFL",icon:"🏈"},{slug:"nhl",name:"NHL",icon:"🏒"},{slug:"nba",name:"NBA",icon:"🏀"},{slug:"cfb",name:"CFB",icon:"🏈"},{slug:"wnba",name:"WNBA",icon:"🏀"}];
const localDay=(d:Date)=>{const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return get("year")+"-"+get("month")+"-"+get("day")};
const dateLabel=(d:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",month:"short",day:"numeric"}).format(new Date(d));
const timeLabel=(d:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",hour:"numeric",minute:"2-digit"}).format(new Date(d))+" ET";
export default function HomeShowcase(){
 const [expanded,setExpanded]=useState(false);
 const [games,setGames]=useState<Item[]>([]);
 const [loaded,setLoaded]=useState(false);
 const [failed,setFailed]=useState(0);
 const [predictions,setPredictions]=useState<Prediction[]>([]);
 const [rankingLoaded,setRankingLoaded]=useState(false);
 const [menuOpen,setMenuOpen]=useState(false);
 const [searchOpen,setSearchOpen]=useState(false);
 const [searchQuery,setSearchQuery]=useState("");
 const [searchResults,setSearchResults]=useState<{sport:Sport;name:string;team:string}[]>([]);
 const [searchBusy,setSearchBusy]=useState(false);
 useEffect(()=>{let live=true;Promise.all(SPORTS.map(async s=>{try{const r=await fetch("/api/game-slate?sport="+s.slug,{cache:"no-store"});if(!r.ok)throw Error("unavailable");const d=await r.json();return {items:(Array.isArray(d.games)?d.games:[]).map((g:Game)=>({...g,sport:s.slug})),failed:false};}catch{return {items:[] as Item[],failed:true};}})).then(results=>{if(live){setGames(results.flatMap(r=>r.items));setFailed(results.filter(r=>r.failed).length);setLoaded(true);}});return()=>{live=false};},[]);
 useEffect(()=>{let active=true;const configs:{sport:Sport;markets:string[]}[]=[{sport:"nfl",markets:["passing_yards","receiving_yards","rushing_yards"]},{sport:"nhl",markets:["shots_on_goal","saves","goals"]},{sport:"nba",markets:["points","rebounds","assists"]},{sport:"cfb",markets:["passing_yards","receiving_yards"]},{sport:"wnba",markets:["points","rebounds"]}];Promise.all(configs.map(async config=>{const results=await Promise.all(config.markets.map(async market=>{try{const r=await fetch("/api/"+config.sport+"/rankings?market="+market,{cache:"no-store"});if(!r.ok)return [];const d=await r.json();if(d.success===false)return [];const rows=Array.isArray(d.rows)?d.rows:Array.isArray(d.rankings)?d.rankings:Array.isArray(d.players)?d.players:Array.isArray(d.data?.rows)?d.data.rows:[];return rows.map((p:any)=>{const name=String(p.playerName||p.name||p.player?.name||"");const line=Number(p.sportsbookLine??p.line??p.propLine??p.marketLine??p.bookLine);const gi=Number(p.giScore??p.gi??p.gi_score??p.intelligenceScore);const photo=String(p.headshot||p.playerPhoto||p.photo||p.player?.headshot||"");return {sport:config.sport,playerName:name,headshot:photo,market:market.replaceAll("_"," "),line,gi,team:String(p.teamName||p.team||""),status:String(p.resultStatus||"")}}).filter((p:Prediction)=>p.playerName&&Number.isFinite(p.line)&&p.line>0&&Number.isFinite(p.gi)&&p.gi>0&&p.status!=="miss"&&p.status!=="void").slice(0,10)}catch{return []}}));return results.flat().sort((a,b)=>b.gi-a.gi)[0]||null})).then(all=>{if(active){setPredictions(all.filter((p):p is Prediction=>p!==null));setRankingLoaded(true)}});return()=>{active=false}},[]);
 useEffect(()=>{const query=searchQuery.trim().toLowerCase();if(!searchOpen||query.length<2){setSearchResults([]);setSearchBusy(false);return}let cancelled=false;const delay=setTimeout(async()=>{setSearchBusy(true);const config:[Sport,string[]][]=[["nfl",["passing_yards","receiving_yards"]],["nhl",["shots_on_goal","saves"]],["nba",["points","rebounds"]],["cfb",["passing_yards"]],["wnba",["points"]]];const data=await Promise.all(config.flatMap(([sport,markets])=>markets.map(async market=>{try{const response=await fetch("/api/"+sport+"/rankings?market="+market,{cache:"no-store"});if(!response.ok)return [];const json=await response.json();const rows=Array.isArray(json.rows)?json.rows:Array.isArray(json.rankings)?json.rankings:[];return rows.map((p:any)=>({sport,name:String(p.playerName||p.name||""),team:String(p.teamName||p.team||"")})).filter((p:{name:string})=>p.name.toLowerCase().includes(query))}catch{return []}})));if(!cancelled){const unique=new Map<string,{sport:Sport;name:string;team:string}>();for(const p of data.flat()){unique.set(p.sport+":"+p.name,p)}setSearchResults([...unique.values()].slice(0,15));setSearchBusy(false)}},350);return()=>{cancelled=true;clearTimeout(delay)}},[searchOpen,searchQuery]);
 const today=localDay(new Date());
 const todays=useMemo(()=>games.filter(g=>{try{return localDay(new Date(g.date))===today}catch{return false}}),[games,today]);
 const featured=SPORTS.slice(0,expanded?5:3);
 const featuredPredictions=featured.map(s=>({sport:s,prediction:predictions.find(p=>p.sport===s.slug)}));
 const ordered=useMemo(()=>{const selected=SPORTS.slice(0,expanded?5:3);return selected.map(s=>todays.filter(g=>g.sport===s.slug).sort((a,b)=>({in:0,pre:1,post:2}[a.state]-{in:0,pre:1,post:2}[b.state])||Date.parse(a.date)-Date.parse(b.date))[0]).filter((g):g is Item=>Boolean(g))},[todays,expanded]);
 const live=todays.filter(g=>g.state==="in").length;
 const upcoming=todays.filter(g=>g.state==="pre").length;
 return <main className="shRoot"><div className="shWrap">
  <header className="shHeader"><Link href="/" className="shBrand"><Image src="/brand/sach-sports-crown-logo.png" alt="Sach Sports crowned S" width={80} height={80} priority/><span><b>SACH</b> SPORTS</span></Link><div className="shHeaderIcons"><button type="button" onClick={()=>{setSearchOpen(v=>!v);setMenuOpen(false)}} aria-expanded={searchOpen} aria-label="Search players" title="Search players">⌕</button><button type="button" onClick={()=>{setMenuOpen(v=>!v);setSearchOpen(false)}} aria-expanded={menuOpen} aria-label="Open navigation menu">☰</button></div></header>
  <nav className="shNav" aria-label="Main navigation"><Link className="shSelected" href="/">HOME</Link>{SPORTS.map(s=><Link key={s.slug} href={"/"+s.slug}>{s.name}</Link>)}</nav>{menuOpen&&<div className="shOverlayMenu" aria-label="Site menu"><Link href="/" onClick={()=>setMenuOpen(false)}>Home</Link>{SPORTS.map(s=><Link href={"/"+s.slug} key={s.slug} onClick={()=>setMenuOpen(false)}>{s.name} Dashboard</Link>)}<button type="button" onClick={()=>{setMenuOpen(false);setSearchOpen(true)}}>Search Players ↗</button></div>}{searchOpen&&<div className="shSearchPanel"><label htmlFor="shPlayerSearch">Search players across active sports</label><div className="shSearchInputRow"><input id="shPlayerSearch" type="search" autoFocus placeholder="Enter a player name…" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)}/><button type="button" onClick={()=>setSearchOpen(false)} aria-label="Close search">✕</button></div><div className="shSearchResults">{searchBusy?<p>Searching player rankings…</p>:searchQuery.trim().length<2?<p>Enter at least two letters.</p>:searchResults.length?searchResults.map(p=><Link key={p.sport+":"+p.name} href={"/"+p.sport+"?player="+encodeURIComponent(p.name)}><strong>{p.name}</strong><span>{p.sport.toUpperCase()} · {p.team}</span></Link>):<p>No matching players in available rankings.</p>}</div></div>}
  <section className="shHero"><div className="shHeroContent"><h1>YOUR <em>GAME.</em><br/>OUR INTELLIGENCE.</h1><p>Player data <i>•</i> Game context <i>•</i> Smarter predictions</p></div><div className="shHeroArtwork" aria-hidden="true"><span className="shHeroAthlete shHeroFootball"/><span className="shHeroAthlete shHeroBasketball"/><span className="shHeroAthlete shHeroHockey"/></div></section>
  <section className="shCenters"><div className="shSectionTitle"><h2>ACTIVE INTELLIGENCE CENTERS</h2><button onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded}>{expanded?"SHOW LESS":"VIEW ALL"} <span>→</span></button></div><div className="shSportGrid">{SPORTS.slice(0,expanded?5:3).map(s=><Link className={"shSportCard shSport-"+s.slug} href={"/"+s.slug} key={s.slug}><div className="shSportIcon" aria-hidden="true" /><div className="shSportBottom"><strong>{s.name}</strong></div><span className="shCircleArrow">›</span></Link>)}</div></section>
  <section className="shIntel"><div className="shIntelTitle"><h2>TODAY’S INTELLIGENCE</h2><span>▦ &nbsp;{new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",weekday:"short",month:"short",day:"numeric",year:"numeric"}).format(new Date())}</span></div><div className="shStats">
   <div><span className="shStatHead"><b><MetricIcon kind="games"/></b> GAMES</span><strong>{loaded?todays.length:"…"}</strong><small>{loaded&&failed===0?live+" live · "+upcoming+" upcoming":"Checking league slates"}</small></div>
   <div><span className="shStatHead"><b><MetricIcon kind="props"/></b> PLAYER PROPS</span><strong>{rankingLoaded?predictions.length:"…"}</strong><small>{rankingLoaded?"Featured eligible props":"Loading props"}</small></div>
   <div><span className="shStatHead"><b><MetricIcon kind="predictions"/></b> PREDICTIONS</span><strong>{rankingLoaded?predictions.length:"…"}</strong><small>{rankingLoaded?"Featured predictions":"Loading predictions"}</small></div>
   <div><span className="shStatHead"><b><MetricIcon kind="hit"/></b> HIT RATE</span><strong className="shPendingMetric">0%</strong><small>No settled predictions yet</small></div>
  </div></section>
  <div className="shBottomGrid">
   <section className="shBottomSection"><div className="shPanel"><div className="shSectionTitle shPanelHeading"><h2>TODAY’S GAMES</h2></div><div className="shGameList">{featured.map(s=>{const g=ordered.find(item=>item.sport===s.slug);return g?<Link href={"/"+g.sport} className="shGame" key={g.sport+g.id}><div className="shTeam">{g.awayLogo?<img src={g.awayLogo} alt=""/>:<span>◉</span>}<b>{g.awayAbbr}</b><small>{g.awayRecord||""}</small></div><span className="shAt">@</span><div className="shTeam">{g.homeLogo?<img src={g.homeLogo} alt=""/>:<span>◉</span>}<b>{g.homeAbbr}</b><small>{g.homeRecord||""}</small></div><div className="shWhen"><b>{dateLabel(g.date)}</b><span>{g.state==="pre"?timeLabel(g.date):g.state==="in"?g.status:"Final"}</span></div></Link>:<div className="shGame shGameEmpty" key={s.slug}><strong>{s.name}</strong><span>{!loaded?"Loading schedule…":failed===SPORTS.length?"Schedule unavailable":"No game today"}</span></div>})}</div></div></section>
   <section className="shBottomSection"><div className="shPanel"><div className="shSectionTitle shPanelHeading"><h2>TOP PREDICTIONS TODAY</h2></div><div className="shPredList">{featuredPredictions.map(({sport,prediction:p})=>p?<Link className="shPredictionRow" href={"/"+sport.slug} key={sport.slug}>{p.headshot?<img src={p.headshot} alt="" loading="lazy"/>:<span className="shPlayerFallback">{sport.name}</span>}<span className="shPlayerDetails"><strong>{p.playerName}</strong><small>{sport.name} · {p.market}</small><small>O/U {p.line}</small></span><span className="shPlayerGI"><small>GI</small>{Math.round(p.gi)}</span></Link>:<Link className="shPredictionRow shPredictionMissing" href={"/"+sport.slug} key={sport.slug}><span className="shPlayerFallback">{sport.name}</span><span className="shPlayerDetails"><strong>{sport.name}</strong><small>{rankingLoaded?"No eligible prediction today":"Checking predictions…"}</small><small>Open player rankings →</small></span></Link>)}</div></div></section>
  </div>
  <footer className="shFooter">© SACH SPORTS · THE INTELLIGENCE EDGE</footer>
 </div></main>;
}
