import { NextRequest, NextResponse } from "next/server";
import { getGameFeed } from "@/lib/mlb-server";
import { loadNbaGameRosters } from "@/lib/nba";
import { loadCbbGameRosters } from "@/lib/cbb";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;

type SportKey = "mlb" | "nfl" | "cfb" | "nba" | "wnba" | "nhl" | "soccer" | "cbb";
type RosterPlayer = { playerId:string; playerName:string; position:string; starter:boolean; active:boolean; headshot:string };
type Roster = { teamId:string; teamName:string; teamAbbr:string; teamLogo:string; side:"away"|"home"|""; players:RosterPlayer[] };
const text=(v:any)=>v==null?"":String(v);
function flattenRosterAthletes(payload:any){const raw=Array.isArray(payload?.athletes)?payload.athletes:[];const out:any[]=[];for(const item of raw){const nested=item?.items||item?.athletes;if(Array.isArray(nested)&&nested.length)out.push(...nested);else out.push(item)}return out}
function normalizeRosterPlayer(raw:any):RosterPlayer|null{const athlete=raw?.athlete&&typeof raw.athlete==="object"?raw.athlete:raw;const id=text(athlete?.id);if(!id)return null;return{playerId:id,playerName:text(athlete?.displayName||athlete?.fullName||"Player"),position:text(athlete?.position?.abbreviation||athlete?.position?.name||""),starter:Boolean(raw?.starter),active:raw?.didNotPlay!==true&&text(athlete?.status?.type).toLowerCase()!=="inactive",headshot:text(athlete?.headshot?.href||"")}}
async function fetchJson(url:string){const r=await fetch(url,{cache:"no-store",headers:{Accept:"application/json","User-Agent":"Sach-Sports/1.0"}});if(!r.ok)throw new Error(`Provider ${r.status}`);return r.json()}
function espnPath(sport:SportKey,league:string){if(sport==="nfl")return"football/nfl";if(sport==="cfb")return"football/college-football";if(sport==="nba")return"basketball/nba";if(sport==="wnba")return"basketball/wnba";if(sport==="cbb")return"basketball/mens-college-basketball";if(sport==="soccer")return`soccer/${encodeURIComponent(league)}`;return""}
async function espnRosters(sport:Exclude<SportKey,"mlb"|"nhl">,gameId:string,league:string):Promise<Roster[]>{
  const path=espnPath(sport,league);if(!path)return[];const summary=await fetchJson(`https://site.api.espn.com/apis/site/v2/sports/${path}/summary?event=${encodeURIComponent(gameId)}`);const competition=summary?.header?.competitions?.[0]||{};const competitors=Array.isArray(competition?.competitors)?competition.competitors:[];const sideByTeam=new Map<string,"away"|"home"|"">(competitors.map((c:any)=>[text(c?.team?.id),c?.homeAway==="away"?"away":c?.homeAway==="home"?"home":""]));const groups=Array.isArray(summary?.boxscore?.players)?summary.boxscore.players:[];const out:Roster[]=[];
  for(const group of groups){const team=group?.team||{};const players:RosterPlayer[]=[];for(const stat of group?.statistics||[])for(const row of stat?.athletes||[]){const p=normalizeRosterPlayer(row);if(p)players.push(p)}const dedup=[...new Map(players.map(p=>[p.playerId,p])).values()].sort((a,b)=>Number(b.starter)-Number(a.starter)||a.playerName.localeCompare(b.playerName));if(dedup.length)out.push({teamId:text(team?.id),teamName:text(team?.displayName||team?.name||"Team"),teamAbbr:text(team?.abbreviation||""),teamLogo:text(team?.logo||""),side:sideByTeam.get(text(team?.id))||"",players:dedup})}
  if(out.length>=2)return out;
  const teams=competitors.map((c:any)=>c?.team||{}).filter((team:any)=>text(team?.id));const fallback=await Promise.all(teams.map(async(team:any):Promise<Roster|null>=>{try{const payload=await fetchJson(`https://site.api.espn.com/apis/site/v2/sports/${path}/teams/${encodeURIComponent(text(team?.id))}/roster`);const players=flattenRosterAthletes(payload).map(normalizeRosterPlayer).filter((p):p is RosterPlayer=>Boolean(p)).sort((a,b)=>Number(b.starter)-Number(a.starter)||a.playerName.localeCompare(b.playerName));return{teamId:text(team?.id),teamName:text(team?.displayName||team?.name||payload?.team?.displayName||"Team"),teamAbbr:text(team?.abbreviation||payload?.team?.abbreviation||""),teamLogo:text(team?.logo||payload?.team?.logo||""),side:sideByTeam.get(text(team?.id))||"",players}}catch{return null}}));return fallback.filter((x):x is Roster=>Boolean(x));
}
async function mlbRosters(gamePk:string):Promise<Roster[]>{const feed:any=await getGameFeed(gamePk);const teams=feed?.liveData?.boxscore?.teams||{},gameTeams=feed?.gameData?.teams||{},out:Roster[]=[];for(const side of ["away","home"] as const){const source=teams?.[side]||{},team=gameTeams?.[side]||{};const players=(Object.values(source?.players||{}) as any[]).map((entry:any)=>{const person=entry?.person||{},id=text(person?.id);if(!id)return null;return{playerId:id,playerName:text(person?.fullName||"Player"),position:text(entry?.position?.abbreviation||entry?.position?.name||""),starter:Boolean(entry?.battingOrder)||Boolean(entry?.stats?.batting?.gamesStarted),active:true,headshot:`https://img.mlbstatic.com/mlb-photos/image/upload/w_180,q_auto:best/v1/people/${id}/headshot/67/current`} as RosterPlayer}).filter((p):p is RosterPlayer=>Boolean(p)).sort((a,b)=>Number(b.starter)-Number(a.starter)||a.playerName.localeCompare(b.playerName));out.push({teamId:text(team?.id),teamName:text(team?.name||side),teamAbbr:text(team?.abbreviation||""),teamLogo:team?.id?`https://www.mlbstatic.com/team-logos/${team.id}.svg`:"",side,players})}return out}
async function nhlRosters(gameId:string):Promise<Roster[]>{const payload=await fetchJson(`https://api-web.nhle.com/v1/gamecenter/${encodeURIComponent(gameId)}/boxscore`);const out:Roster[]=[];for(const side of ["away","home"] as const){const team=payload?.[`${side}Team`]||{},stats=payload?.playerByGameStats?.[side]||{},players:RosterPlayer[]=[];for(const bucket of ["forwards","defense","goalies"])for(const row of stats?.[bucket]||[]){const id=text(row?.playerId);if(!id)continue;const name=text(row?.name?.default)||[text(row?.firstName?.default),text(row?.lastName?.default)].filter(Boolean).join(" ")||"Player";players.push({playerId:id,playerName:name,position:text(row?.position||(bucket==="goalies"?"G":"")),starter:Boolean(row?.starter),active:true,headshot:text(row?.headshot||"")})}out.push({teamId:text(team?.id),teamName:text(team?.name?.default||team?.commonName?.default||team?.abbrev||"Team"),teamAbbr:text(team?.abbrev||""),teamLogo:text(team?.logo||""),side,players:[...new Map(players.map(p=>[p.playerId,p])).values()]})}return out}

export async function GET(req:NextRequest){const sport=String(req.nextUrl.searchParams.get("sport")||"").toLowerCase() as SportKey;const gameId=req.nextUrl.searchParams.get("gameId")||"";const league=req.nextUrl.searchParams.get("league")||"eng.1";const allowed:SportKey[]=["mlb","nfl","cfb","nba","wnba","nhl","soccer","cbb"];if(!allowed.includes(sport)||!gameId)return NextResponse.json({success:false,rosters:[],error:"Invalid game detail request"},{status:400});try{let rosters:Roster[]=[];if(sport==="mlb")rosters=await mlbRosters(gameId);else if(sport==="nba")rosters=(await loadNbaGameRosters(gameId)).map((r:any,i:number)=>({...r,side:i===0?"away":i===1?"home":""}));else if(sport==="cbb")rosters=(await loadCbbGameRosters(gameId)).map((r:any,i:number)=>({...r,side:i===0?"away":i===1?"home":""}));else if(sport==="nhl")rosters=await nhlRosters(gameId);else rosters=await espnRosters(sport as Exclude<SportKey,"mlb"|"nhl">,gameId,league);return NextResponse.json({success:true,sport,gameId,rosters,updatedAt:new Date().toISOString()});}catch(error){return NextResponse.json({success:false,sport,gameId,rosters:[],error:error instanceof Error?error.message:"Game detail unavailable",updatedAt:new Date().toISOString()},{status:500});}}
