import Link from "next/link";
import {CfbPlayerHistory} from "@/components/cfb-player-history";
import {getCfbAthleteDetails,getEspnCfbSchedule} from "@/lib/cfb-server";
import type {CfbMarketKey} from "@/lib/cfb";
import {CFB_MARKETS} from "@/lib/cfb";
export const dynamic="force-dynamic";
function norm(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,"")}
function label(k:CfbMarketKey){return CFB_MARKETS.find(x=>x[0]===k)?.[2]||"Player Intelligence"}
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const{id}=await params,qs=await searchParams;const get=(k:string)=>typeof qs[k]==="string"?String(qs[k]):"";
 const[details,schedule]=await Promise.all([getCfbAthleteDetails(id),getEspnCfbSchedule()]);
 const name=details.name!=="CFB Player"?details.name:(get("name")||"CFB Player"),team=details.teamName||get("team"),matchup=get("matchup"),img=details.headshot||get("img");
 const requested=(get("market")||"passing_yards") as CfbMarketKey,market=CFB_MARKETS.some(x=>x[0]===requested)?requested:"passing_yards";
 const gi=get("gi")||"—",prob=get("prob")||"—",line=get("line")||"—",projection=get("projection")||"—";
 const teamId=String(details.teamId||""),teamKey=norm(team);
 const game=schedule.find((g:any)=>teamId&&(String(g.awayTeamId)===teamId||String(g.homeTeamId)===teamId))||schedule.find((g:any)=>teamKey&&(norm(String(g.awayTeam||""))===teamKey||norm(String(g.homeTeam||""))===teamKey));
 const state=String(game?.state||"pre").toLowerCase(),completed=Boolean(game?.completed)||state==="post",live=state==="in"&&!completed;
 const status=completed?"FINAL":live?"LIVE":"SCHEDULED",detail=game?(live||completed?`${game.awayTeam} ${game.awayScore??0} · ${game.homeTeam} ${game.homeScore??0}`:`${game.awayTeam} @ ${game.homeTeam}`):(matchup||"Matchup pending");
 const teamLogo=game?(String(game.awayTeamId)===teamId?game.awayLogo:game.homeLogo):"";
 return <main className="p"><Link href="/" className="menu">▦⌄</Link><Link className="back" href="/cfb">← Back to CFB</Link>
 <section className="head"><div className="visual">{img?<img src={img} alt=""/>:<div className="avatar">CFB</div>}{teamLogo?<img className="logo" src={teamLogo} alt=""/>:null}</div><div><h1>{name}</h1><p>{team}{details.position?` · ${details.position}`:""}</p>{matchup?<b>{matchup}</b>:null}</div></section>
 <section className={`game ${live?"live":completed?"final":""}`}><div><small>GAME STATUS</small><strong>{status}</strong><span>{game?.status||"Game status pending"}</span></div><div className="gd">{detail}</div></section>
 <section className="strip"><b>{label(market)}</b><span>GI {gi}{prob!=="—"?` · ${prob}%`:""}</span></section>
 <div className="metrics"><article><span>SPORTSBOOK LINE</span><b>{line}</b></article><article><span>MODEL PROJECTION</span><b>{projection}</b></article><article><span>POSITION</span><b>{details.position||"—"}</b></article><article><span>SEASON</span><b>2026</b></article></div>
 <section className="why"><h3>Why This Player Ranks Here</h3><p>The sportsbook line is compared with verified college game history to build the model projection and prediction score. No missing line or result is invented.</p></section>
 {details.teamId?<Link className="roster" href={`/cfb/team/${encodeURIComponent(details.teamId)}?name=${encodeURIComponent(team)}&logo=${encodeURIComponent(teamLogo||"")}`}>Open {team} roster →</Link>:null}
 <CfbPlayerHistory playerId={id} playerName={name} market={market} marketLabel={label(market)} line={line}/>
 <style>{`.p{max-width:780px;margin:0 auto;padding:10px 14px 80px;color:#fff}.menu{display:grid;place-items:center;width:58px;height:58px;border:2px solid #20df7f;border-radius:16px;background:#0c0e0d;color:#fff;text-decoration:none}.back{display:block;width:max-content;margin:10px 0 20px auto;padding:11px 16px;border:2px solid #34373d;border-radius:14px;background:#101112;color:#fff;text-decoration:none}.head{display:grid;grid-template-columns:92px 1fr;gap:16px;align-items:center;border:1px solid #34373d;border-radius:18px;padding:18px;background:#111214}.visual{position:relative;width:82px;height:82px}.head img,.avatar{width:78px;height:78px;border-radius:50%;border:3px solid #d9b85d;object-fit:cover}.avatar{display:grid;place-items:center;color:#d9b85d;font-weight:900}.head .logo{position:absolute;right:-5px;bottom:-5px;width:30px;height:30px;border:2px solid #20df7f;background:#111214;object-fit:contain}.head h1{margin:0;font-size:28px}.head p{color:#a9acb3;margin:5px 0}.head b{color:#d9b85d}.game{display:grid;grid-template-columns:1fr 1fr;gap:12px;align-items:center;margin:14px 0 0;border:1.5px solid #d9b85d;border-radius:13px;padding:12px 14px;background:#0d0f10}.game.live{border-color:#20df7f}.game.final{border-color:#4b4f55}.game small{display:block;color:#8f949c;font-size:10px}.game strong{display:block;color:#d9b85d}.game.live strong{color:#20df7f}.game span{color:#a9acb3;font-size:12px}.gd{text-align:right;font-size:12px;font-weight:850}.strip{display:flex;justify-content:space-between;margin:14px 0;border:1px solid #20df7f;border-radius:12px;padding:14px;background:#111214}.strip span{color:#d9b85d;font-weight:900}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.metrics article{border:1px solid #34373d;border-left:4px solid #20df7f;border-radius:12px;padding:12px;background:#111214}.metrics span{display:block;color:#9da1a8;font-size:11px}.metrics b{display:block;margin-top:6px}.why{border:1px solid #d9b85d;border-radius:14px;padding:16px;margin-top:18px;background:#101112}.why h3{color:#d9b85d;margin-top:0}.why p{line-height:1.5;color:#d7d8db}.roster{display:block;margin-top:14px;border:2px solid #34373d;border-radius:14px;padding:13px;text-align:center;color:#fff;text-decoration:none;background:#0d0f10}@media(max-width:600px){.metrics{grid-template-columns:repeat(2,1fr)}.game{grid-template-columns:1fr}.gd{text-align:left}}`}</style></main>
}
