"""Dedicated WNBA Player Intelligence page."""
from html import escape
import pandas as pd, streamlit as st
from data.wnba_stats import WNBA_BASELINE_SEASON, wnba_headshot_url
p=st.session_state.get('wnba_selected_player') or {};prop=str(st.session_state.get('wnba_selected_prop') or 'WNBA Market')
if not p:
 st.warning('No WNBA player is selected.');
 if st.button('← Back to WNBA'):st.switch_page('pages/wnba.py')
 st.stop()
st.markdown('''<style>.head{display:grid;grid-template-columns:76px minmax(0,1fr);gap:12px;align-items:center;padding:12px;background:linear-gradient(118deg,#101112,#111315 68%,rgba(25,217,120,.07));border:1.5px solid #30343a;border-radius:14px}.photo{width:72px;height:72px;border-radius:50%;overflow:hidden;background:#f4f4f4;border:2px solid rgba(214,179,92,.86)}.photo img{width:100%;height:100%;object-fit:contain}.copy h2{margin:0}.copy p{margin:3px 0;color:#a7abb2;font-size:.78rem}.copy strong{color:#f6c84c;font-size:.76rem}.strip{display:flex;justify-content:space-between;background:#0c0e0f;border:1px solid rgba(25,217,120,.55);border-radius:10px;padding:8px 10px;margin:7px 0 11px}.strip span{color:#19d978;font-weight:900}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.metric{background:#101112;border:1.5px solid rgba(214,179,92,.62);border-left:3px solid #19d978;border-radius:10px;padding:7px 6px}.metric span{display:block;color:#9da2aa;font-size:.61rem}.metric strong{font-size:.94rem}.intel{background:#101112;border:1.5px solid #34373c;border-radius:11px;padding:12px;margin:10px 0}.intel h3{color:#f6c84c}.intel p{color:#c5c9ce;font-size:.78rem;line-height:1.5}.intel b{color:#19d978}div[class*="st-key-back_to_wnba_player"]{display:flex!important;justify-content:flex-end!important}</style>''',unsafe_allow_html=True)
if st.button('← Back to WNBA',key='back_to_wnba_player'):st.switch_page('pages/wnba.py')
def n(k):
 v=pd.to_numeric(p.get(k),errors='coerce');return '—' if pd.isna(v) else f'{float(v):.1f}'
name=escape(str(p.get('player_name','WNBA Player')));team=escape(str(p.get('team','—')));pid=p.get('player_id');photo=wnba_headshot_url(int(pid)) if pd.notna(pid) else '';img=f'<div class="photo"><img src="{photo}"></div>' if photo else '<div class="photo"></div>';rank=p.get('rank','—');move=escape(str(p.get('rank_movement','—')));metric=escape(str(p.get('metric_label','Per Game')));val=n('ranking_value');gp=pd.to_numeric(p.get('games_played'),errors='coerce');games='—' if pd.isna(gp) else str(int(gp))
st.markdown(f'<div class="head">{img}<div class="copy"><h2>{name}</h2><p>{team} · {WNBA_BASELINE_SEASON} regular season</p><strong>{escape(prop)} intelligence</strong></div></div><div class="strip"><b>{escape(prop)}</b><span>#{rank} · {move} · {metric} {val}</span></div>',unsafe_allow_html=True)
st.markdown(f'<div class="grid"><div class="metric"><span>PTS/G</span><strong>{n("points_per_game")}</strong></div><div class="metric"><span>REB/G</span><strong>{n("rebounds_per_game")}</strong></div><div class="metric"><span>AST/G</span><strong>{n("assists_per_game")}</strong></div><div class="metric"><span>3PM/G</span><strong>{n("threes_per_game")}</strong></div><div class="metric"><span>STL/G</span><strong>{n("steals_per_game")}</strong></div><div class="metric"><span>BLK/G</span><strong>{n("blocks_per_game")}</strong></div><div class="metric"><span>MIN/G</span><strong>{n("minutes_per_game")}</strong></div><div class="metric"><span>GAMES</span><strong>{games}</strong></div></div>',unsafe_allow_html=True)
st.markdown(f'''<div class="intel"><h3>🧠 Today's Intelligence</h3><p><b>Market position:</b> {name} ranks #{rank} in {escape(prop)} from the verified {WNBA_BASELINE_SEASON} regular-season baseline at {val} per game.</p><p><b>Production profile:</b> {n("points_per_game")} PTS/G · {n("rebounds_per_game")} REB/G · {n("assists_per_game")} AST/G · {n("threes_per_game")} 3PM/G.</p><p><b>Role and sample reliability:</b> {games} games at {n("minutes_per_game")} minutes per game provide the workload context behind the ranking.</p><p><b>Live prediction layer:</b> Sportsbook line, opponent-specific matchup edge, probability and GI score will only appear when those live WNBA inputs are connected; none are fabricated here.</p></div>''',unsafe_allow_html=True)
