import { CFB_MARKETS, type CfbMarketKey, type CfbRankingRow, cleanName, safeNumber } from "@/lib/cfb";

const ESPN_SCOREBOARD="https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard";
const ODDS_BASE="https://api.the-odds-api.com/v4";
const ODDS_SPORT="americanfootball_ncaaf";
const ODDS_MARKETS:Record<CfbMarketKey,string>={
  passing_yards:"player_pass_yds", pass_completions:"player_pass_completions", rushing_yards:"player_rush_yds",
  receiving_yards:"player_reception_yds", receptions:"player_receptions", anytime_td:"player_anytime_td", first_td:"player_1st_td"
};
const SGO_STATS:Record<CfbMarketKey,string[]>={
  passing_yards:["passing_yards","passingYards"], pass_completions:["completions","passing_completions","passingCompletions"],
  rushing_yards:["rushing_yards","rushingYards"], receiving_yards:["receiving_yards","receivingYards"],
  receptions:["receptions","receiving_receptions"], anytime_td:["touchdowns","anytimeTouchdown","anytime_touchdown"], first_td:["firstTouchdown","first_touchdown"]
};

async function json(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:"no-store"});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
export async function getEspnCfbSchedule(){
  const payload=await json(`${ESPN_SCOREBOARD}?limit=200&groups=80`);return (payload.events||[]).map((e:any)=>{const c=e.competitions?.[0]||{};const h=(c.competitors||[]).find((x:any)=>x.homeAway==="home")||{};const a=(c.competitors||[]).find((x:any)=>x.homeAway==="away")||{};const status=e.status?.type||{};return {id:String(e.id),date:e.date,awayTeam:a.team?.displayName||"Away",homeTeam:h.team?.displayName||"Home",awayLogo:a.team?.logo||"",homeLogo:h.team?.logo||"",awayScore:a.score??"",homeScore:h.score??"",status:status.shortDetail||status.description||"Scheduled",completed:Boolean(status.completed),venue:c.venue?.fullName||""}});
}

function americanProb(v:any){const n=Number(v);if(!Number.isFinite(n)||n===0)return null;return Math.round((n>0?100/(n+100):Math.abs(n)/(Math.abs(n)+100))*1000)/10}
function median(xs:number[]){if(!xs.length)return null;const a=[...xs].sort((x,y)=>x-y);const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2}
function sgoOdds(e:any){const raw=e.odds||e.markets||[];if(Array.isArray(raw))return raw;if(raw&&typeof raw==="object")return Object.entries(raw).flatMap(([k,v]:any)=>Array.isArray(v)?v:(v&&typeof v==="object"?[{oddID:k,...v}]:[]));return []}
function sgoMatchup(e:any){const t=e.teams||{};const away=e.awayTeamName||e.awayTeam||t.away?.name;const home=e.homeTeamName||e.homeTeam||t.home?.name;return away&&home?`${away} @ ${home}`:String(e.name||e.eventName||"")}

export async function getCfbMarketRows(market:CfbMarketKey){
  const sgoKey=process.env.SPORTSGAMEODDS_API_KEY;
  if(sgoKey){try{const now=new Date(),end=new Date(now.getTime()+10*86400000);const qs=new URLSearchParams({leagueID:"NCAAF",oddsAvailable:"true",finalized:"false",startsAfter:now.toISOString(),startsBefore:end.toISOString(),limit:"100"});const p=await json(`https://api.sportsgameodds.com/v2/events?${qs}`,{headers:{"x-api-key":sgoKey}});const rows:any[]=[];for(const e of p.data||[]){for(const o of sgoOdds(e)){const stat=String(o.statID||o.statId||"");if(!SGO_STATS[market].includes(stat))continue;const side=String(o.sideID||o.side||"").toLowerCase();if(!["anytime_td","first_td"].includes(market)&&side!=="over")continue;if(["anytime_td","first_td"].includes(market)&&["no","under"].includes(side))continue;const playerName=String(o.statEntityName||o.playerName||o.participantName||"").trim();if(!playerName)continue;rows.push({eventId:String(e.eventID||e.id||""),matchup:sgoMatchup(e),playerName,line:safeNumber(o.bookOverUnder),price:safeNumber(o.fairOdds??o.bookOdds),prob:americanProb(o.fairOdds??o.bookOdds),bookmakerCount:o.byBookmaker&&typeof o.byBookmaker==="object"?Object.keys(o.byBookmaker).length:0})}}
    if(rows.length)return rows;}catch{}}
  const key=process.env.THE_ODDS_API_KEY;if(!key)return [];
  try{const events=await json(`${ODDS_BASE}/sports/${ODDS_SPORT}/events?apiKey=${encodeURIComponent(key)}&dateFormat=iso`);const rows:any[]=[];for(const e of (events||[]).slice(0,80)){let p:any;try{p=await json(`${ODDS_BASE}/sports/${ODDS_SPORT}/events/${e.id}/odds?apiKey=${encodeURIComponent(key)}&regions=us&markets=${ODDS_MARKETS[market]}&oddsFormat=american&dateFormat=iso`)}catch{continue}for(const b of p.bookmakers||[])for(const m of b.markets||[])if(m.key===ODDS_MARKETS[market])for(const o of m.outcomes||[]){const name=String(o.name||"").toLowerCase();if(!["anytime_td","first_td"].includes(market)&&name!=="over")continue;if(["anytime_td","first_td"].includes(market)&&["no","under"].includes(name))continue;const playerName=String(o.description||(["anytime_td","first_td"].includes(market)?o.name:"")).trim();if(!playerName)continue;rows.push({eventId:String(e.id),matchup:`${e.away_team} @ ${e.home_team}`,playerName,line:safeNumber(o.point),price:safeNumber(o.price),prob:americanProb(o.price),book:b.key})}}
    const grouped=new Map<string,any[]>();for(const r of rows){const k=`${cleanName(r.playerName)}|${cleanName(r.matchup)}`;grouped.set(k,[...(grouped.get(k)||[]),r])}return [...grouped.values()].map(g=>({eventId:g[0].eventId,matchup:g[0].matchup,playerName:g[0].playerName,line:median(g.map(x=>x.line).filter((x:any)=>x!=null)),price:median(g.map(x=>x.price).filter((x:any)=>x!=null)),prob:median(g.map(x=>x.prob).filter((x:any)=>x!=null)),bookmakerCount:new Set(g.map(x=>x.book)).size}));}catch{return []}
}

async function espnProfile(name:string){try{const p=await json(`https://site.web.api.espn.com/apis/search/v2?query=${encodeURIComponent(name)}&limit=12&sport=football`);const nodes:any[]=[];const walk=(v:any)=>{if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==="object"){nodes.push(v);Object.values(v).forEach(walk)}};walk(p);const target=cleanName(name);const matches=nodes.map(n=>{const display=String(n.displayName||n.fullName||n.name||n.title||"");const id=n.id;let score=display&&cleanName(display)===target?100:0;if(String(n).toLowerCase().includes("football"))score+=10;return {score,n,display,id}}).filter(x=>x.id&&x.score>0).sort((a,b)=>b.score-a.score);const n=matches[0]?.n||{};const img=n.headshot?.href||n.image?.href||n.image?.url||n.images?.[0]?.href||"";const team=n.team?.displayName||n.team?.name||n.teamName||"";return {id:String(matches[0]?.id||""),headshot:String(img||""),teamName:String(team||""),position:String(n.position?.abbreviation||n.positionAbbreviation||"")}}catch{return {id:"",headshot:"",teamName:"",position:""}}}

function gi(prob:number|null,books:number){return Math.round(Math.max(1,Math.min(99,(prob??50)*0.82+Math.min(18,books*3)))*10)/10}
export async function getCfbRankings(market:CfbMarketKey):Promise<CfbRankingRow[]>{const rows=await getCfbMarketRows(market);const out:CfbRankingRow[]=[];for(const r of rows.slice(0,50)){const profile=await espnProfile(r.playerName);const p=r.prob??50;out.push({rank:0,playerId:profile.id||cleanName(r.playerName),playerName:r.playerName,teamName:profile.teamName||r.matchup.split(" @ ")[0]||"CFB",headshot:profile.headshot,matchup:r.matchup,giScore:gi(p,r.bookmakerCount||0),modelProbability:p,sportsbookLine:r.line,sportsbookProbability:p,bookmakerCount:r.bookmakerCount||0,perGame:null,seasonTotal:null,gamesPlayed:null,season:2026,summary:`Sportsbook-backed ${CFB_MARKETS.find(x=>x[0]===market)?.[2]||market} ranking. ${r.bookmakerCount||0} book${(r.bookmakerCount||0)===1?"":"s"} contributing.` ,marketBacked:true})}out.sort((a,b)=>b.giScore-a.giScore);return out.map((r,i)=>({...r,rank:i+1}))}
export async function getPropQualifiedGames(){const markets:CfbMarketKey[]=CFB_MARKETS.map(x=>x[0]);const all=await Promise.all(markets.map(async m=>[m,await getCfbMarketRows(m)] as const));const map=new Map<string,{matchup:string;props:CfbMarketKey[]}>();for(const [m,rows] of all){for(const r of rows){const k=cleanName(r.matchup);const cur:{matchup:string;props:CfbMarketKey[]}=map.get(k)??{matchup:r.matchup,props:[]};if(!cur.props.includes(m))cur.props.push(m);map.set(k,cur)}}return [...map.values()]}
