import {cleanNhlName,loadNhlOverview,nhlHeadshot,playerBaseline,todaysNhlGames,type NhlMarketKey} from "@/lib/nhl";
const OWLS_URL="https://api.owlsinsight.com/api/v1/nhl/props";
const norm=(v:any)=>String(v??"").toLowerCase().replace(/[^a-z0-9]/g,"");
const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const median=(xs:number[])=>{const a=xs.filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
function match(v:any,m:NhlMarketKey){const x=norm(v);const a:Record<NhlMarketKey,string[]>={shots_on_goal:["shotsongoal","playershotsongoal","shots"],points:["points","playerpoints"],goals:["goals","playergoals","anytimegoalscorer"],assists:["assists","playerassists"],blocked_shots:["blockedshots","blocks","playerblockedshots"],goalie_saves:["goaliesaves","saves","playersaves"]};return a[m].includes(x)}
async function owls(){const key=process.env.OWLS_INSIGHT_API_KEY;if(!key)return null;const r=await fetch(OWLS_URL,{headers:{Authorization:`Bearer ${key}`,Accept:"application/json"},cache:"no-store"});if(!r.ok)return null;return r.json()}
function board(payload:any,m:NhlMarketKey){const map=new Map<string,any>();for(const g of Array.isArray(payload?.data)?payload.data:[]){const away=String(g.awayTeam||g.away_team||""),home=String(g.homeTeam||g.home_team||""),matchup=away&&home?`${away} @ ${home}`:String(g.name||""),gameTime=String(g.commenceTime||g.commence_time||g.startTime||g.date||"");for(const book of Array.isArray(g.books)?g.books:[])for(const p of Array.isArray(book.props)?book.props:[]){if(!match(p.category??p.market??p.type,m))continue;const playerName=String(p.playerName||p.player_name||p.name||"").trim(),line=num(p.line??p.point??p.total);if(!playerName||line==null)continue;const k=`${cleanNhlName(playerName)}|${cleanNhlName(matchup)}`,cur=map.get(k)||{playerName,matchup,gameTime,lines:[],books:new Set<string>()};cur.lines.push(line);cur.books.add(String(book.key||book.name||"book"));map.set(k,cur)}}return [...map.values()].map((x:any)=>({...x,line:median(x.lines),bookmakerCount:x.books.size}))}
export async function buildNhlRankings(m:NhlMarketKey){const overview=await loadNhlOverview(),payload=await owls().catch(()=>null),b=payload?board(payload,m):[],byName=new Map(overview.players.map(p=>[cleanNhlName(p.playerName),p]));const todayGames=todaysNhlGames(overview.games);const activeTeams=new Set(todayGames.flatMap(g=>[g.awayAbbr,g.homeAbbr]));const rows:any[]=[];for(const x of b){const p=byName.get(cleanNhlName(x.playerName));if(!p||!activeTeams.has(p.team))continue;const game=todayGames.find(g=>[g.awayAbbr,g.homeAbbr].includes(p.team));if(!game)continue;const base=playerBaseline(p,m),edge=base!=null&&x.line!=null?base-x.line:null,reliability=Math.min(1,(p.gamesPlayed||0)/30),gi=Math.round((55+Math.min(25,Math.abs(edge||0)*7)+reliability*15)*10)/10;rows.push({playerId:p.playerId,playerName:p.playerName,teamName:p.team,teamLogo:p.team===game.awayAbbr?game.awayLogo:game.homeLogo,matchup:`${game.awayTeam} @ ${game.homeTeam}`,gameTime:game.tipoff||"",gameId:game.gameId,gameState:game.state,gameStatus:game.status,headshot:nhlHeadshot(p.playerId,p.team),sportsbookLine:x.line,bookmakerCount:x.bookmakerCount,modelProjection:base,modelProbability:edge==null?null:Math.max(50,Math.min(82,Math.round((55+Math.abs(edge)*5+reliability*5)*10)/10)),giScore:gi,prediction:edge==null?null:edge>=0?"OVER":"UNDER",marketBacked:true,summary:`${overview.season} baseline ${base==null?"loading":base.toFixed(2)} vs verified line ${x.line}. GI adds recent-season sample reliability, role and active matchup context.`})}
 const used=new Set(rows.map(x=>cleanNhlName(x.playerName)));for(const p of overview.players){if(rows.length>=25)break;if(used.has(cleanNhlName(p.playerName))||!activeTeams.has(p.team))continue;const base=playerBaseline(p,m);if(base==null)continue;const game=todayGames.find(g=>[g.awayAbbr,g.homeAbbr].includes(p.team));if(!game)continue;rows.push({playerId:p.playerId,playerName:p.playerName,teamName:p.team,teamLogo:p.team===game.awayAbbr?game.awayLogo:game.homeLogo,matchup:`${game.awayTeam} @ ${game.homeTeam}`,gameTime:game.tipoff||"",gameId:game.gameId,gameState:game.state,gameStatus:game.status,headshot:nhlHeadshot(p.playerId,p.team),sportsbookLine:null,bookmakerCount:0,modelProjection:base,modelProbability:null,giScore:Math.round((55+Math.min(1,(p.gamesPlayed||0)/30)*15+Math.min(20,base*3))*10)/10,prediction:null,marketBacked:false,summary:`${overview.season} statistical baseline ${base.toFixed(2)}. No verified sportsbook line is currently available, so this is a model-only active-slate ranking and is not graded.`})}
 rows.sort((a,b)=>b.giScore-a.giScore);return{success:true,market:m,rows:rows.slice(0,25).map((x,i)=>({...x,rank:i+1})),updatedAt:new Date().toISOString(),source:payload?"Owls Insight NHL props + NHL API":"NHL API active-slate model (Owls NHL props unavailable)"}}
