export const WNBA_SEASON = "2026";

export const WNBA_MARKETS = ["Points", "Rebounds", "Assists", "3-Pointers Made", "Points + Rebounds + Assists (PRA)", "Points + Rebounds", "Points + Assists", "Rebounds + Assists", "Steals", "Blocks"] as const;
export type WnbaMarket = (typeof WNBA_MARKETS)[number];

export type WnbaPlayer = { playerId:number; playerName:string; team:string; gamesPlayed:number|null; minutesPerGame:number|null; pointsPerGame:number|null; reboundsPerGame:number|null; assistsPerGame:number|null; threesPerGame:number|null; stealsPerGame:number|null; blocksPerGame:number|null };
export type WnbaRanking = WnbaPlayer & { rank:number; market:WnbaMarket; rankingValue:number; metricLabel:string };
export type WnbaGame = { gameId:string; tipoff:string|null; awayTeam:string; awayAbbr:string; awayLogo:string|null; awayScore:number|null; homeTeam:string; homeAbbr:string; homeLogo:string|null; homeScore:number|null; status:string; state:string };
export type WnbaOverview = { season:string; updatedAt:string; rankings:Record<WnbaMarket,WnbaRanking[]>; games:WnbaGame[]; warnings:string[] };

type JsonRecord = Record<string, unknown>;
const STATS_URL="https://site.web.api.espn.com/apis/common/v3/sports/basketball/wnba/statistics/byathlete";
const SCOREBOARD_URL="https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/scoreboard";
const averageAliases={minutesPerGame:["avgminutes","minutespergame","minpergame"],pointsPerGame:["avgpoints","pointspergame","ptspergame"],reboundsPerGame:["avgrebounds","reboundspergame","rebpergame"],assistsPerGame:["avgassists","assistspergame","astpergame"],threesPerGame:["avgthreepointfieldgoalsmade","threepointfieldgoalsmadepergame","threepointersmadepergame","fg3mpergame"],stealsPerGame:["avgsteals","stealspergame","stlpergame"],blocksPerGame:["avgblocks","blockspergame","blkpergame"]} as const;
const totalAliases={minutesPerGame:["minutes","min"],pointsPerGame:["points","pts"],reboundsPerGame:["rebounds","rebs","reb"],assistsPerGame:["assists","ast"],threesPerGame:["threepointfieldgoalsmade","threepointersmade","fg3m","3pm"],stealsPerGame:["steals","stl"],blocksPerGame:["blocks","blk"]} as const;

function sum(...values:Array<number|null>):number|null{return values.some(v=>v===null)?null:values.reduce<number>((t,v)=>t+(v??0),0)}
const marketMetric:Record<WnbaMarket,{label:string;value:(p:WnbaPlayer)=>number|null}>={
  Points:{label:"PTS/G",value:p=>p.pointsPerGame},Rebounds:{label:"REB/G",value:p=>p.reboundsPerGame},Assists:{label:"AST/G",value:p=>p.assistsPerGame},"3-Pointers Made":{label:"3PM/G",value:p=>p.threesPerGame},
  "Points + Rebounds + Assists (PRA)":{label:"PRA/G",value:p=>sum(p.pointsPerGame,p.reboundsPerGame,p.assistsPerGame)},"Points + Rebounds":{label:"P+R/G",value:p=>sum(p.pointsPerGame,p.reboundsPerGame)},"Points + Assists":{label:"P+A/G",value:p=>sum(p.pointsPerGame,p.assistsPerGame)},"Rebounds + Assists":{label:"R+A/G",value:p=>sum(p.reboundsPerGame,p.assistsPerGame)},Steals:{label:"STL/G",value:p=>p.stealsPerGame},Blocks:{label:"BLK/G",value:p=>p.blocksPerGame}
};
function record(v:unknown):JsonRecord{return v&&typeof v==="object"&&!Array.isArray(v)?v as JsonRecord:{}}
function list(v:unknown):unknown[]{return Array.isArray(v)?v:[]}
function text(v:unknown):string{return typeof v==="string"||typeof v==="number"?String(v):""}
function number(v:unknown):number|null{if(typeof v==="number"&&Number.isFinite(v))return v;const n=Number(String(v??"").replaceAll(",",""));return Number.isFinite(n)?n:null}
function normalized(v:unknown):string{return text(v).toLowerCase().replace(/[^a-z0-9]/g,"")}
function firstStat(stats:Map<string,number>,aliases:readonly string[]):number|null{for(const alias of aliases){const v=stats.get(alias);if(v!==undefined)return v}return null}
function perGame(stats:Map<string,number>,field:keyof typeof averageAliases,games:number|null):number|null{const avg=firstStat(stats,averageAliases[field]);if(avg!==null)return avg;const total=firstStat(stats,totalAliases[field]);return total!==null&&games&&games>0?total/games:null}
function categoryLabels(payload:JsonRecord):string[][]{return list(payload.categories).map(v=>{const c=record(v);return list(c.labels??c.names).map(text)})}
function flattenStats(entry:JsonRecord,fallback:string[][]):Map<string,number>{const out=new Map<string,number>();list(entry.categories).forEach((v,i)=>{const c=record(v);const labels=list(c.labels??c.names).length?list(c.labels??c.names).map(text):(fallback[i]??[]);const totals=c.totals??c.values;if(totals&&typeof totals==="object"&&!Array.isArray(totals)){Object.entries(totals as JsonRecord).forEach(([label,value])=>{const n=number(value);if(n!==null)out.set(normalized(label),n)});return}list(totals).forEach((value,index)=>{const n=number(value);if(n!==null&&labels[index])out.set(normalized(labels[index]),n)})});return out}
function parsePlayers(payloads:JsonRecord[]):WnbaPlayer[]{const players=new Map<number,WnbaPlayer>();payloads.forEach(payload=>{const labels=categoryLabels(payload);list(payload.athletes).forEach(v=>{const entry=record(v),athlete=record(entry.athlete);const id=number(text(athlete.id??athlete.uid).split(":").at(-1)?.split("~").at(-1));const name=text(athlete.displayName??athlete.fullName);if(id===null||!name)return;const team=record(athlete.team),stats=flattenStats(entry,labels),games=firstStat(stats,["gamesplayed","games","gp"]);players.set(id,{playerId:id,playerName:name,team:text(athlete.teamShortName??athlete.teamAbbreviation??team.abbreviation)||"—",gamesPlayed:games,minutesPerGame:perGame(stats,"minutesPerGame",games),pointsPerGame:perGame(stats,"pointsPerGame",games),reboundsPerGame:perGame(stats,"reboundsPerGame",games),assistsPerGame:perGame(stats,"assistsPerGame",games),threesPerGame:perGame(stats,"threesPerGame",games),stealsPerGame:perGame(stats,"stealsPerGame",games),blocksPerGame:perGame(stats,"blocksPerGame",games)})})});return [...players.values()]}
function buildRankings(players:WnbaPlayer[]):Record<WnbaMarket,WnbaRanking[]>{return Object.fromEntries(WNBA_MARKETS.map(market=>{const metric=marketMetric[market];const rows=players.filter(p=>(p.gamesPlayed??0)>=10&&metric.value(p)!==null).sort((a,b)=>((metric.value(b)??0)-(metric.value(a)??0))||((b.minutesPerGame??0)-(a.minutesPerGame??0))).slice(0,25).map((p,i)=>({...p,rank:i+1,market,rankingValue:metric.value(p)??0,metricLabel:metric.label}));return [market,rows]})) as Record<WnbaMarket,WnbaRanking[]>}
async function fetchJson(url:string,revalidate:number):Promise<JsonRecord>{const response=await fetch(url,{headers:{Accept:"application/json","User-Agent":"Sach-Sports/1.0"},next:{revalidate}});if(!response.ok)throw new Error(`Data provider returned ${response.status}`);return record(await response.json())}
async function loadPlayers():Promise<WnbaPlayer[]>{const base={region:"us",lang:"en",contentorigin:"espn",isqualified:"false",limit:"500",sort:"offensive.avgPoints:desc",season:WNBA_SEASON,seasontype:"2"};const firstParams=new URLSearchParams({...base,page:"1"});const first=await fetchJson(`${STATS_URL}?${firstParams}`,21600);const pages=Math.min(number(record(first.pagination).pages)??1,8);const remaining=await Promise.all(Array.from({length:Math.max(0,pages-1)},(_,i)=>fetchJson(`${STATS_URL}?${new URLSearchParams({...base,page:String(i+2)})}`,21600)));return parsePlayers([first,...remaining])}
function dateKey(date:Date):string{return date.toISOString().slice(0,10).replaceAll("-","")}
function competitor(c:JsonRecord,side:"home"|"away"):JsonRecord{return record(list(c.competitors).find(v=>text(record(v).homeAway)===side))}
async function loadGames():Promise<WnbaGame[]>{const now=new Date(),start=new Date(now),end=new Date(now);start.setUTCDate(start.getUTCDate()-1);end.setUTCDate(end.getUTCDate()+14);const payload=await fetchJson(`${SCOREBOARD_URL}?dates=${dateKey(start)}-${dateKey(end)}&limit=200`,300);return list(payload.events).flatMap(v=>{const e=record(v),c=record(list(e.competitions)[0]);if(!Object.keys(c).length)return[];const away=competitor(c,"away"),home=competitor(c,"home"),at=record(away.team),ht=record(home.team),status=record(record(e.status).type);return[{gameId:text(e.id),tipoff:text(e.date)||null,awayTeam:text(at.displayName)||"Away",awayAbbr:text(at.abbreviation),awayLogo:text(at.logo)||null,awayScore:number(away.score),homeTeam:text(ht.displayName)||"Home",homeAbbr:text(ht.abbreviation),homeLogo:text(ht.logo)||null,homeScore:number(home.score),status:text(status.shortDetail??status.description)||"Scheduled",state:text(status.state)||"pre"}]})}
export async function loadWnbaOverview():Promise<WnbaOverview>{const warnings:string[]=[];const [pr,gr]=await Promise.allSettled([loadPlayers(),loadGames()]);const players=pr.status==="fulfilled"?pr.value:[],games=gr.status==="fulfilled"?gr.value:[];if(pr.status==="rejected")warnings.push("Player rankings are temporarily unavailable.");if(gr.status==="rejected")warnings.push("The WNBA schedule is temporarily unavailable.");return{season:WNBA_SEASON,updatedAt:new Date().toISOString(),rankings:buildRankings(players),games,warnings}}
export function wnbaHeadshot(playerId:number):string{return `https://a.espncdn.com/i/headshots/wnba/players/full/${playerId}.png`}
