import {cleanWnbaName,type WnbaMarketKey} from "@/lib/wnba";
export type SavedWnbaPrediction={key:string;gameDate:string;gameTime:string;gameId?:string;matchup:string;market:WnbaMarketKey;playerId:string;playerName:string;teamName:string;teamLogo?:string;headshot?:string;sportsbookLine:number|null;modelProjection:number|null;modelProbability:number|null;pickSide:"OVER"|"UNDER";giScore:number;bookmakerCount:number;savedAt:string;status:"pending"|"hit"|"miss"|"push"|"void";actual:number|null;gradedAt:string|null};
const PREFIX="wnba_predictions_";
const runtime=new Map<string,SavedWnbaPrediction[]>();
const rk=(m:WnbaMarketKey,d:string)=>`${m}|${d}`;
function url(){return (process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||"").replace(/\/$/,"")}
function keys(){return [process.env.SUPABASE_SECRET_KEY,process.env.SUPABASE_SERVICE_ROLE_KEY,process.env.SUPABASE_KEY,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY].map(v=>String(v||"").trim()).filter((v,i,a)=>v&&a.indexOf(v)===i)}
function headers(k:string,prefer="return=representation"){const h:any={apikey:k,"Content-Type":"application/json",Accept:"application/json",Prefer:prefer};if(!k.startsWith("sb_secret_")&&!k.startsWith("sb_publishable_"))h.Authorization=`Bearer ${k}`;return h}
export function wnbaDay(v:Date|string){const d=typeof v==="string"?new Date(v):v;if(Number.isNaN(d.getTime()))return"";const p=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Toronto",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d),g=(t:string)=>p.find(x=>x.type===t)?.value||"";return `${g("year")}-${g("month")}-${g("day")}`}
async function read(m:WnbaMarketKey,day:string){const u=url(),ks=keys();if(!u||!ks.length)return{connected:false,rows:[] as any[]};const q=`source_snapshots?select=id,payload,created_at&source_name=eq.${encodeURIComponent(PREFIX+m)}&game_date=eq.${encodeURIComponent(day)}&order=created_at.desc&limit=20`;for(const k of ks){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);const r=await fetch(`${u}/rest/v1/${q}`,{headers:headers(k),cache:"no-store",signal:c.signal});clearTimeout(t);if(r.ok)return{connected:true,rows:await r.json()};if(r.status===401||r.status===403)continue}catch{}}return{connected:false,rows:[] as any[]}}
function merge(rows:any[]){const map=new Map<string,SavedWnbaPrediction>();for(const row of [...rows].reverse())for(const p of Array.isArray(row?.payload?.predictions)?row.payload.predictions:[]){if(!p?.key)continue;const old=map.get(p.key);if(!old){map.set(p.key,p);continue}map.set(p.key,old.status==="pending"&&p.status==="pending"&&Date.parse(p.savedAt||"")>=Date.parse(old.savedAt||"")?p:{...old,status:p.status!=="pending"?p.status:old.status,actual:p.actual??old.actual,gradedAt:p.gradedAt||old.gradedAt})}return [...map.values()]}
async function write(m:WnbaMarketKey,day:string,predictions:SavedWnbaPrediction[],id?:string){runtime.set(rk(m,day),predictions);const u=url();for(const k of keys()){try{const endpoint=id?`${u}/rest/v1/source_snapshots?id=eq.${encodeURIComponent(id)}`:`${u}/rest/v1/source_snapshots`;const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);const r=await fetch(endpoint,{method:id?"PATCH":"POST",headers:headers(k,"return=minimal"),body:JSON.stringify({source_name:PREFIX+m,game_date:day,payload:{predictions},created_at:new Date().toISOString()}),signal:c.signal});clearTimeout(t);if(r.ok)return true;if(r.status===401||r.status===403)continue}catch{}}return false}
export async function getWnbaPredictions(m:WnbaMarketKey,day:string){const x=await read(m,day);const db=merge(x.rows),mem=runtime.get(rk(m,day))||[],predictions=merge([{payload:{predictions:db}},{payload:{predictions:mem}}]);if(predictions.length)runtime.set(rk(m,day),predictions);return{connected:x.connected||predictions.length>0,predictions,id:x.rows?.[0]?.id as string|undefined}}
export async function saveWnbaPredictions(m:WnbaMarketKey,rows:any[]){const today=wnbaDay(new Date()),buckets=new Map<string,{id?:string;map:Map<string,SavedWnbaPrediction>}>();for(const row of rows){const day=wnbaDay(row.gameTime||new Date());if(!day||day<today||row.sportsbookLine==null||!row.playerId)continue;let b=buckets.get(day);if(!b){const old=await getWnbaPredictions(m,day);b={id:old.id,map:new Map(old.predictions.map(x=>[x.key,x]))};buckets.set(day,b)}const key=`${day}|${m}|${row.playerId}|${cleanWnbaName(row.matchup||"")}`;const old=b.map.get(key);const next:SavedWnbaPrediction={key,gameDate:day,gameTime:String(row.gameTime||""),gameId:String(row.gameId||""),matchup:String(row.matchup||""),market:m,playerId:String(row.playerId),playerName:String(row.playerName),teamName:String(row.teamName),teamLogo:String(row.teamLogo||""),headshot:String(row.headshot||""),sportsbookLine:Number(row.sportsbookLine),modelProjection:row.modelProjection==null?null:Number(row.modelProjection),modelProbability:row.modelProbability==null?null:Number(row.modelProbability),pickSide:row.prediction||"OVER",giScore:Number(row.giScore||0),bookmakerCount:Number(row.bookmakerCount||0),savedAt:new Date().toISOString(),status:"pending",actual:null,gradedAt:null};b.map.set(key,old&&old.status!=="pending"?old:next)}let ok=true;for(const[day,b]of buckets)ok=(await write(m,day,[...b.map.values()],b.id))&&ok;return ok}
export async function saveWnbaGrades(m:WnbaMarketKey,day:string,predictions:SavedWnbaPrediction[],id?:string){return write(m,day,predictions,id)}
